// src/pages/Abastecimentos.jsx
import React, { useState, useMemo, useEffect } from 'react';
import { base44 } from '@/api/base44Client';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { motion } from 'framer-motion';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Plus, Pencil, Trash2, Fuel, Car, Trash, Upload } from 'lucide-react';
import FuelImport from '@/components/fueling/FuelImport';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';
import PageHeader from '@/components/shared/PageHeader';
import FuelForm from '@/components/fueling/FuelForm';
import FuelFilters from '@/components/fueling/FuelFilters';
import FuelSummaryCards from '@/components/fueling/FuelSummaryCards';
import FuelCharts from '@/components/fueling/FuelCharts';
import { format } from 'date-fns';

const formatCurrency = (v) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(v || 0);
const formatNum = (v) => v != null ? Number(v).toLocaleString('pt-BR') : '-';

export default function Abastecimentos() {
  const queryClient = useQueryClient();
  const [showForm, setShowForm] = useState(false);
  const [editRecord, setEditRecord] = useState(null);
  const [deleteId, setDeleteId] = useState(null);
  const [showImport, setShowImport] = useState(false);
  const [showBulkDelete, setShowBulkDelete] = useState(false);
  const [bulkCostName, setBulkCostName] = useState('');
  const [bulkCostType, setBulkCostType] = useState('');
  const [filters, setFilters] = useState({ dateFrom: '', dateTo: '', category: '', costName: '', costType: '', plate: '' });
  const [currentPage, setCurrentPage] = useState(1);
  const PAGE_SIZE = 8;

  const { data: records = [], isLoading } = useQuery({
    queryKey: ['fuel-records'],
    queryFn: () => base44.entities.FuelRecord.list('-date', 10000)
  });

  const { data: vehicles = [] } = useQuery({
    queryKey: ['vehicles'],
    queryFn: () => base44.entities.Vehicle.list()
  });

  const { data: vehicleCategories = [] } = useQuery({
    queryKey: ['vehicle-categories-filter'],
    queryFn: () => base44.entities.VehicleCategory.list()
  });

  const vehicleMap = useMemo(() => {
    const map = {};
    vehicles.forEach((v) => {map[v.plate] = v;});
    return map;
  }, [vehicles]);

  const createMutation = useMutation({
    mutationFn: (data) => base44.entities.FuelRecord.create(data),
    onSuccess: () => {queryClient.invalidateQueries({ queryKey: ['fuel-records'] });setShowForm(false);}
  });

  const updateMutation = useMutation({
    mutationFn: ({ id, data }) => base44.entities.FuelRecord.update(id, data),
    onSuccess: () => {queryClient.invalidateQueries({ queryKey: ['fuel-records'] });setShowForm(false);setEditRecord(null);}
  });

  const deleteMutation = useMutation({
    mutationFn: (id) => base44.entities.FuelRecord.delete(id),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['fuel-records'] })
  });

  const bulkDeleteMutation = useMutation({
    mutationFn: async ({ costName, costType }) => {
      const toDelete = records.filter((r) =>
      r.cost_name === costName && (!costType || r.cost_type === costType)
      );
      await Promise.all(toDelete.map((r) => base44.entities.FuelRecord.delete(r.id)));
      return toDelete.length;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['fuel-records'] });
      setShowBulkDelete(false);
      setBulkCostName('');
      setBulkCostType('');
    }
  });

  const bulkDeleteCount = useMemo(() => {
    if (!bulkCostName) return 0;
    return records.filter((r) =>
    r.cost_name === bulkCostName && (!bulkCostType || r.cost_type === bulkCostType)
    ).length;
  }, [records, bulkCostName, bulkCostType]);

  const handleSubmit = (data) => {
    if (editRecord) updateMutation.mutate({ id: editRecord.id, data });else
    createMutation.mutate(data);
  };

  const filtered = useMemo(() => {
    return records.filter((r) => {
      if (filters.dateFrom && r.date < filters.dateFrom) return false;
      if (filters.dateTo && r.date > filters.dateTo) return false;
      if (filters.category && filters.category !== 'all' && r.category_name !== filters.category) return false;
      if (filters.costName && filters.costName !== 'all' && r.cost_name !== filters.costName) return false;
      if (filters.costType && filters.costType !== 'all' && r.cost_type !== filters.costType) return false;
      if (filters.plate && filters.plate !== 'all' && r.plate !== filters.plate) return false;
      return true;
    });
  }, [records, filters]);

  const categories = useMemo(() => vehicleCategories.filter((c) => c.is_active).map((c) => c.name).sort(), [vehicleCategories]);
  const costNames = useMemo(() => [...new Set(records.map((r) => r.cost_name).filter(Boolean))].sort(), [records]);
  const costTypes = useMemo(() => [...new Set(records.map((r) => r.cost_type).filter(Boolean))].sort(), [records]);
  const plates = useMemo(() => [...new Set(records.map((r) => r.plate).filter(Boolean))].sort(), [records]);

  const bulkCostTypes = useMemo(() => {
    if (!bulkCostName) return costTypes;
    return [...new Set(records.filter((r) => r.cost_name === bulkCostName).map((r) => r.cost_type).filter(Boolean))].sort();
  }, [records, bulkCostName, costTypes]);

  const totalValue = filtered.reduce((s, r) => s + (r.total_value || 0), 0);

  const totalPages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE));
  const paginatedRecords = filtered.slice((currentPage - 1) * PAGE_SIZE, currentPage * PAGE_SIZE);

  // Reset page when filters change
  useEffect(() => {setCurrentPage(1);}, [filters]);

  return (
    <div className="p-6 space-y-6">
      <PageHeader
        title="Abastecimentos"
        subtitle="Controle de custos com combustíveis"
        icon={Fuel}
        iconColor="bg-warning/10"
        breadcrumbs={[{ label: 'Dashboard', path: '/' }, { label: 'Abastecimentos' }]} />
      

      {/* Summary cards */}
      <FuelSummaryCards records={filtered} />

      {/* Charts */}
      <FuelCharts records={filtered} />

      {/* Filters */}
      <FuelFilters filters={filters} onChange={setFilters} categories={categories} costNames={costNames} costTypes={costTypes} plates={plates} />

      {/* Table */}
      <Card className="overflow-hidden border shadow-sm">
        <div className="flex items-center justify-between gap-4 p-4 border-b bg-card">
          <p className="text-sm font-semibold">{filtered.length} registro(s)</p>
          <div className="flex items-center gap-2">
            <Button onClick={() => {setEditRecord(null);setShowForm(true);}} className="gap-2 hover:bg-warning/90 text-warning-foreground shadow-md shadow-warning/20 bg-[hsl(var(--muted-foreground))]">
              <Plus className="w-4 h-4" /> Lançar
            </Button>
            <Button onClick={() => setShowImport(true)} variant="outline" className="gap-2">
              <Upload className="w-4 h-4" /> Importar
            </Button>
          </div>
        </div>

        {isLoading ?
        <div className="flex items-center justify-center py-16">
            <div className="w-8 h-8 border-4 border-muted border-t-warning rounded-full animate-spin" />
          </div> :

        <div className="overflow-x-auto overflow-y-auto" style={{ maxHeight: '420px' }}>
            <Table>
              <TableHeader>
                <TableRow className="bg-muted/50">
                  <TableHead className="text-xs uppercase tracking-wider font-semibold text-muted-foreground">Data</TableHead>
                  <TableHead className="text-xs uppercase tracking-wider font-semibold text-muted-foreground">Veículo</TableHead>
                  <TableHead className="text-xs uppercase tracking-wider font-semibold text-muted-foreground">Categoria</TableHead>
                  <TableHead className="text-xs uppercase tracking-wider font-semibold text-muted-foreground">Tipo de Custo</TableHead>
                  <TableHead className="text-xs uppercase tracking-wider font-semibold text-muted-foreground">Custo</TableHead>
                  <TableHead className="text-xs uppercase tracking-wider font-semibold text-muted-foreground text-right">Litros</TableHead>
                  <TableHead className="text-xs uppercase tracking-wider font-semibold text-muted-foreground text-right">Valor (R$)</TableHead>
                  <TableHead className="text-xs uppercase tracking-wider font-semibold text-muted-foreground text-right">KM</TableHead>
                  <TableHead className="text-xs uppercase tracking-wider font-semibold text-muted-foreground">Fornecedor</TableHead>
                  <TableHead className="w-20 text-right text-xs uppercase tracking-wider font-semibold text-muted-foreground">Ações</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filtered.length === 0 ?
              <TableRow>
                    <TableCell colSpan={13} className="text-center py-12 text-muted-foreground">
                      Nenhum registro encontrado
                    </TableCell>
                  </TableRow> :

              paginatedRecords.map((r, idx) => {
                const veh = vehicleMap[r.plate];
                const model = veh?.vehicle_model || r.vehicle_model;
                const category = veh?.category_name || r.category_name;
                const costTypeColors = {
                  DIESEL: 'bg-blue-50 text-blue-700 border border-blue-200',
                  GASOLINA: 'bg-orange-50 text-orange-600 border border-orange-200',
                  ETANOL: 'bg-green-50 text-green-700 border border-green-200',
                  ARLA: 'bg-purple-50 text-purple-700 border border-purple-200'
                };
                const costTypeColor = costTypeColors[r.cost_type?.toUpperCase()] || 'bg-muted text-muted-foreground border';
                return (
                  <motion.tr
                    key={r.id}
                    initial={{ opacity: 0, y: 4 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: idx * 0.01 }}
                    className="border-b hover:bg-muted/30 transition-colors">
                    
                        {/* Data */}
                        <TableCell className="py-3 text-sm font-medium whitespace-nowrap">
                          {r.date ? format(new Date(r.date + 'T12:00:00'), 'dd/MM/yyyy') : '-'}
                        </TableCell>

                        {/* Veículo: placa + modelo */}
                        <TableCell className="py-3 whitespace-nowrap">
                          <div className="flex items-center gap-2">
                            <div className="w-7 h-7 rounded-lg bg-slate-100 flex items-center justify-center flex-shrink-0">
                              <Car className="w-3.5 h-3.5 text-slate-500" />
                            </div>
                            <div className="flex flex-col">
                              <span className="text-sm font-bold font-mono tracking-widest text-foreground">{r.plate}</span>
                              {model && <span className="text-xs text-muted-foreground leading-tight">{model}</span>}
                            </div>
                          </div>
                        </TableCell>

                        {/* Categoria (automática pela placa) */}
                        <TableCell className="py-3">
                          <Badge variant="outline" className="text-xs font-medium">{category || '-'}</Badge>
                        </TableCell>

                        {/* Tipo de Custo com badge colorido */}
                        <TableCell className="py-3">
                          <span className={`inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-bold ${costTypeColor}`}>
                            <span className="w-1.5 h-1.5 rounded-full bg-current opacity-70" />
                            {r.cost_type}
                          </span>
                        </TableCell>

                        {/* Custo */}
                        <TableCell className="py-3">
                          <Badge className="bg-blue-50 text-blue-700 border border-blue-200 text-xs font-semibold">{r.cost_name}</Badge>
                        </TableCell>

                        {/* Litros */}
                        <TableCell className="py-3 text-sm text-right font-medium tabular-nums">{formatNum(r.quantity)}</TableCell>

                        {/* Valor */}
                        <TableCell className="py-3 text-sm text-right font-semibold text-success tabular-nums">{formatCurrency(r.total_value)}</TableCell>

                        {/* KM */}
                        <TableCell className="py-3 text-sm text-right tabular-nums text-muted-foreground">{r.km ? formatNum(r.km, 0) : '-'}</TableCell>

                        {/* Fornecedor */}
                        <TableCell className="py-3">
                          <div className="flex flex-col max-w-[180px]">
                            <span className="text-xs font-medium text-foreground leading-tight truncate" title={r.supplier}>{r.supplier || '-'}</span>
                            {r.invoice_number && <span className="text-xs text-muted-foreground">Nota: {r.invoice_number}</span>}
                          </div>
                        </TableCell>

                        {/* Ações */}
                        <TableCell className="py-3 text-right">
                          <div className="flex items-center justify-end gap-1">
                            <Button variant="ghost" size="icon" className="h-7 w-7 text-muted-foreground hover:text-primary" onClick={() => {setEditRecord(r);setShowForm(true);}}>
                              <Pencil className="w-3.5 h-3.5" />
                            </Button>
                            <Button variant="ghost" size="icon" className="h-7 w-7 text-muted-foreground hover:text-destructive" onClick={() => setDeleteId(r.id)}>
                              <Trash2 className="w-3.5 h-3.5" />
                            </Button>
                          </div>
                        </TableCell>
                      </motion.tr>);

              })
              }
              </TableBody>
            </Table>
          </div>
        }

        {filtered.length > 0 &&
        <div className="px-4 py-3 bg-muted/30 border-t flex flex-col sm:flex-row items-center justify-between gap-3">
            {/* Info */}
            <div className="flex items-center gap-4 text-xs text-muted-foreground">
              <span>{filtered.length} de {records.length} registro(s)</span>
              <span className="font-semibold text-foreground">Total filtrado: {formatCurrency(totalValue)}</span>
            </div>
            {/* Pagination */}
            <div className="flex items-center gap-1">
              <button
              onClick={() => setCurrentPage(1)}
              disabled={currentPage === 1}
              className="h-7 w-7 flex items-center justify-center rounded-md text-xs border bg-card hover:bg-muted disabled:opacity-40 disabled:cursor-not-allowed transition-colors font-medium">
              «</button>
              <button
              onClick={() => setCurrentPage((p) => Math.max(1, p - 1))}
              disabled={currentPage === 1}
              className="h-7 w-7 flex items-center justify-center rounded-md text-xs border bg-card hover:bg-muted disabled:opacity-40 disabled:cursor-not-allowed transition-colors font-medium">
              ‹</button>

              {Array.from({ length: totalPages }, (_, i) => i + 1).
            filter((p) => p === 1 || p === totalPages || Math.abs(p - currentPage) <= 1).
            reduce((acc, p, idx, arr) => {
              if (idx > 0 && p - arr[idx - 1] > 1) acc.push('...');
              acc.push(p);
              return acc;
            }, []).
            map((p, i) =>
            p === '...' ?
            <span key={`ellipsis-${i}`} className="h-7 w-7 flex items-center justify-center text-xs text-muted-foreground">…</span> :
            <button
              key={p}
              onClick={() => setCurrentPage(p)}
              className={`h-7 w-7 flex items-center justify-center rounded-md text-xs border transition-colors font-medium
                          ${currentPage === p ? 'bg-primary text-primary-foreground border-primary' : 'bg-card hover:bg-muted'}`}>
              {p}</button>
            )
            }

              <button
              onClick={() => setCurrentPage((p) => Math.min(totalPages, p + 1))}
              disabled={currentPage === totalPages}
              className="h-7 w-7 flex items-center justify-center rounded-md text-xs border bg-card hover:bg-muted disabled:opacity-40 disabled:cursor-not-allowed transition-colors font-medium">
              ›</button>
              <button
              onClick={() => setCurrentPage(totalPages)}
              disabled={currentPage === totalPages}
              className="h-7 w-7 flex items-center justify-center rounded-md text-xs border bg-card hover:bg-muted disabled:opacity-40 disabled:cursor-not-allowed transition-colors font-medium">
              »</button>
            </div>
          </div>
        }
      </Card>

      <FuelForm
        open={showForm}
        onClose={() => {setShowForm(false);setEditRecord(null);}}
        onSubmit={handleSubmit}
        isLoading={createMutation.isPending || updateMutation.isPending}
        record={editRecord} />
      

      {/* Bulk Delete Dialog */}
      <Dialog open={showBulkDelete} onOpenChange={(v) => {setShowBulkDelete(v);if (!v) {setBulkCostName('');setBulkCostType('');}}}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2 text-destructive">
              <Trash className="w-5 h-5" /> Excluir por Custo
            </DialogTitle>
          </DialogHeader>
          <div className="space-y-4 py-2">
            <p className="text-sm text-muted-foreground">Selecione o custo e opcionalmente o tipo de custo para excluir <strong>todos</strong> os lançamentos relacionados.</p>
            <div className="space-y-2">
              <Label>Custo *</Label>
              <Select value={bulkCostName} onValueChange={(v) => {setBulkCostName(v);setBulkCostType('');}}>
                <SelectTrigger>
                  <SelectValue placeholder="Selecione o custo..." />
                </SelectTrigger>
                <SelectContent>
                  {costNames.map((n) => <SelectItem key={n} value={n}>{n}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label>Tipo de Custo <span className="text-muted-foreground text-xs">(opcional — deixe em branco para todos)</span></Label>
              <Select value={bulkCostType} onValueChange={setBulkCostType} disabled={!bulkCostName}>
                <SelectTrigger>
                  <SelectValue placeholder="Todos os tipos..." />
                </SelectTrigger>
                <SelectContent>
                  {bulkCostTypes.map((t) => <SelectItem key={t} value={t}>{t}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
            {bulkCostName &&
            <div className="rounded-lg bg-destructive/10 border border-destructive/20 px-4 py-3 text-sm text-destructive font-medium">
                ⚠️ {bulkDeleteCount} lançamento(s) serão excluídos permanentemente.
              </div>
            }
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowBulkDelete(false)}>Cancelar</Button>
            <Button
              variant="destructive"
              disabled={!bulkCostName || bulkDeleteCount === 0 || bulkDeleteMutation.isPending}
              onClick={() => bulkDeleteMutation.mutate({ costName: bulkCostName, costType: bulkCostType })}>
              
              {bulkDeleteMutation.isPending ? 'Excluindo...' : `Excluir ${bulkDeleteCount} registro(s)`}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <FuelImport open={showImport} onClose={() => setShowImport(false)} />

      <AlertDialog open={!!deleteId} onOpenChange={() => setDeleteId(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Confirmar exclusão</AlertDialogTitle>
            <AlertDialogDescription>Tem certeza que deseja excluir este lançamento? Esta ação não pode ser desfeita.</AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancelar</AlertDialogCancel>
            <AlertDialogAction className="bg-destructive hover:bg-destructive/90" onClick={() => {deleteMutation.mutate(deleteId);setDeleteId(null);}}>
              Excluir
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>);

}

// frontend-vue/src/pages/Abastecimentos.vue
<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from "vue";
import { Fuel, Plus, DollarSign, Droplets, Gauge, Car, Pencil, Trash2 } from "lucide-vue-next";
import { toast } from "vue-sonner";
import { Doughnut, Bar } from "vue-chartjs";
import {
  fuelRecords, vehicles, fuelCostTypes,
  type FuelRecord, type Vehicle, type FuelCostType,
} from "@/services/api";
import { useResource } from "@/composables/useResource";
import { formatBRL, formatDate } from "@/lib/utils";
import { seriesColors, palette, baseOptions, brlTick } from "@/lib/charts";
import PageHeader from "@/components/ui/PageHeader.vue";
import Modal from "@/components/ui/Modal.vue";
import Button from "@/components/ui/Button.vue";
import Badge from "@/components/ui/Badge.vue";
import StatCard from "@/components/ui/StatCard.vue";
import ChartCard from "@/components/ui/ChartCard.vue";
import ChartLegend from "@/components/ui/ChartLegend.vue";
import FilterBar from "@/components/ui/FilterBar.vue";
import FormField from "@/components/ui/FormField.vue";
import Spinner from "@/components/ui/Spinner.vue";

const { items, loading, saving, fetchAll, create, update, remove } = useResource<FuelRecord>(
  fuelRecords,
  { created: "Abastecimento lançado!", updated: "Abastecimento atualizado!", removed: "Abastecimento excluído!" },
);
const vehicleList = ref<Vehicle[]>([]);
const costTypes = ref<FuelCostType[]>([]);

onMounted(async () => {
  await Promise.all([
    fetchAll(),
    vehicles.list({ limit: 1000 }).then((v) => (vehicleList.value = v)),
    fuelCostTypes.list({ limit: 1000 }).then((c) => (costTypes.value = c)),
  ]);
});

/* ---------- categoria resolvida pela placa (fallback ao denormalizado) ---------- */
const vehByPlate = computed(() => {
  const m: Record<string, Vehicle> = {};
  for (const v of vehicleList.value) if (v.plate) m[v.plate] = v;
  return m;
});
const catOf = (r: FuelRecord) => vehByPlate.value[r.plate]?.category_name || r.category_name || "";

/* ---------- filtros ---------- */
const filters = reactive({ from: "", to: "", category: "", costName: "", costType: "", plate: "" });
const filtered = computed(() =>
  items.value
    .filter((r) => {
      if (filters.from && (r.date ?? "") < filters.from) return false;
      if (filters.to && (r.date ?? "") > filters.to) return false;
      if (filters.category && catOf(r) !== filters.category) return false;
      if (filters.costName && r.cost_name !== filters.costName) return false;
      if (filters.costType && r.cost_type !== filters.costType) return false;
      if (filters.plate && r.plate !== filters.plate) return false;
      return true;
    })
    // Mais recentes primeiro.
    .sort((a, b) => (b.date ?? "").localeCompare(a.date ?? "")),
);
const hasFilters = computed(() => Object.values(filters).some(Boolean));
function clearFilters() {
  filters.from = filters.to = filters.category = filters.costName = filters.costType = filters.plate = "";
}

const uniqSorted = (arr: (string | undefined | null)[]) =>
  [...new Set(arr.filter(Boolean) as string[])].sort((a, b) => a.localeCompare(b));
const categoryOptions = computed(() => uniqSorted(vehicleList.value.map((v) => v.category_name)));
const costNameOptions = computed(() => uniqSorted(items.value.map((r) => r.cost_name)));
const costTypeOptions = computed(() => uniqSorted(items.value.map((r) => r.cost_type)));
const plateOptions = computed(() => uniqSorted(items.value.map((r) => r.plate)));

/* ---------- resumo (reflete os filtros) ---------- */
const totalValue = computed(() => filtered.value.reduce((s, r) => s + Number(r.total_value || 0), 0));
const totalLiters = computed(() => filtered.value.reduce((s, r) => s + Number(r.quantity || 0), 0));
const kmRange = computed(() => {
  const kms = filtered.value.map((r) => Number(r.km)).filter((v) => v > 0);
  return kms.length ? Math.max(...kms) - Math.min(...kms) : 0;
});
const avgConsumption = computed(() =>
  totalLiters.value > 0 && kmRange.value > 0 ? kmRange.value / totalLiters.value : 0,
);
const num = (v: number, d = 0) =>
  v.toLocaleString("pt-BR", { minimumFractionDigits: d, maximumFractionDigits: d });

const stats = computed(() => [
  { label: "Custo Total", value: formatBRL(totalValue.value), icon: DollarSign, tone: "bg-primary/15 text-primary-hover", highlight: true },
  { label: "Litros Abastecidos", value: `${num(totalLiters.value, 0)} L`, icon: Droplets, tone: "bg-success/10 text-success" },
  { label: "Quilometragem", value: `${num(kmRange.value)} km`, icon: Gauge, tone: "bg-warning/10 text-warning" },
  { label: "Média de Consumo", value: `${num(avgConsumption.value, 1)} km/L`, icon: Fuel, tone: "bg-accent/10 text-accent" },
]);

/* ---------- gráficos ---------- */
const costTypeEntries = computed(() => {
  const acc: Record<string, number> = {};
  for (const r of filtered.value) {
    const k = r.cost_type || "Outros";
    acc[k] = (acc[k] || 0) + Number(r.total_value || 0);
  }
  return Object.entries(acc).sort((a, b) => b[1] - a[1]);
});
const byCostType = computed(() => ({
  labels: costTypeEntries.value.map((e) => e[0]),
  datasets: [{ data: costTypeEntries.value.map((e) => e[1]), backgroundColor: costTypeEntries.value.map((_, i) => seriesColors[i % seriesColors.length]), borderWidth: 0 }],
}));
const costTypeLegend = computed(() =>
  costTypeEntries.value.map(([label, value], i) => ({ label, value, color: seriesColors[i % seriesColors.length] })),
);
const pieOptions = { ...baseOptions, plugins: { legend: { display: false } } };

const monthly = computed(() => {
  const acc: Record<string, { custo: number; litros: number }> = {};
  for (const r of filtered.value) {
    if (!r.date) continue;
    const k = r.date.slice(0, 7);
    (acc[k] ??= { custo: 0, litros: 0 }).custo += Number(r.total_value || 0);
    acc[k].litros += Number(r.quantity || 0);
  }
  const keys = Object.keys(acc).sort();
  const label = (k: string) => { const [y, m] = k.split("-"); return `${m}/${y.slice(2)}`; };
  return {
    labels: keys.map(label),
    datasets: [
      { type: "bar" as const, label: "Custo (R$)", data: keys.map((k) => acc[k].custo), backgroundColor: palette.primary, borderRadius: 6, yAxisID: "y", order: 2 },
      { type: "line" as const, label: "Litros", data: keys.map((k) => acc[k].litros), borderColor: palette.success, backgroundColor: palette.success, tension: 0.35, pointRadius: 3, yAxisID: "y1", order: 1 },
    ],
  };
});
const monthlyOptions = {
  ...baseOptions,
  plugins: { legend: { position: "bottom" as const, labels: { usePointStyle: true, boxWidth: 8, padding: 16 } } },
  scales: {
    x: { grid: { display: false } },
    y: { position: "left" as const, ticks: { callback: brlTick }, grid: { drawOnChartArea: true } },
    y1: { position: "right" as const, ticks: { callback: (v: number | string) => `${v} L` }, grid: { drawOnChartArea: false } },
  },
};

/* ---------- cor da bolinha por tipo de combustível ---------- */
function typeColor(ct?: string) {
  const u = (ct ?? "").toUpperCase();
  if (u.includes("DIESEL")) return u.includes("(T)") ? "#f97316" : "#f59e0b";
  if (u.includes("ETANOL")) return "#10b981";
  if (u.includes("GASOLINA")) return "#ef4444";
  if (u.includes("ARLA")) return "#8b5cf6";
  return "#9ca3af";
}

/* ---------- paginação ---------- */
const page = ref(1);
const pageSize = 10;
const totalPages = computed(() => Math.max(1, Math.ceil(filtered.value.length / pageSize)));
const paged = computed(() => filtered.value.slice((page.value - 1) * pageSize, page.value * pageSize));
watch(filtered, () => { page.value = 1; });
const pageNumbers = computed(() => {
  const t = totalPages.value, c = page.value;
  const out: (number | "...")[] = [];
  for (let p = 1; p <= t; p++) {
    if (p === 1 || p === t || Math.abs(p - c) <= 1) {
      if (out.length && (out[out.length - 1] as number) < p - 1) out.push("...");
      out.push(p);
    }
  }
  return out;
});

/* ---------- formulário ---------- */
const dialogOpen = ref(false);
const editing = ref<FuelRecord | null>(null);
const emptyForm = () => ({
  date: new Date().toISOString().slice(0, 10),
  plate: "", cost_name: "", cost_type: "", quantity: 0, total_value: 0,
  unit: "LT" as "LT" | "UN", km: null as number | null,
  supplier: "", invoice_number: "", observation: "",
});
const form = reactive(emptyForm());
const selectedCostTypeId = ref("");
function selectCostType(id: string) {
  const ct = costTypes.value.find((c) => c.id === id);
  if (ct) { form.cost_type = ct.cost_type; form.cost_name = ct.cost_name; }
}
function openAdd() {
  editing.value = null;
  Object.assign(form, emptyForm());
  selectedCostTypeId.value = "";
  dialogOpen.value = true;
}
function openEdit(row: FuelRecord) {
  editing.value = row;
  Object.assign(form, {
    date: row.date?.slice(0, 10), plate: row.plate, cost_name: row.cost_name,
    cost_type: row.cost_type, quantity: Number(row.quantity), total_value: Number(row.total_value),
    unit: row.unit, km: row.km, supplier: row.supplier ?? "",
    invoice_number: row.invoice_number ?? "", observation: row.observation ?? "",
  });
  selectedCostTypeId.value =
    costTypes.value.find((c) => c.cost_type === row.cost_type && c.cost_name === row.cost_name)?.id ?? "";
  dialogOpen.value = true;
}
async function submit() {
  if (!form.plate) return toast.error("Selecione o veículo (placa)");
  if (!form.cost_type) return toast.error("Selecione o tipo de custo");
  const payload = { ...form, km: form.km || null };
  const ok = editing.value ? await update(editing.value.id, payload) : await create(payload);
  if (ok) dialogOpen.value = false;
}

/* ---------- exclusão ---------- */
const deleteId = ref<string | null>(null);
async function confirmDelete() {
  if (deleteId.value) await remove(deleteId.value);
  deleteId.value = null;
}
</script>

<template>
  <div class="w-full p-6 md:p-10">
    <PageHeader title="Abastecimentos" subtitle="Lançamentos de combustível" :icon="Fuel">
      <template #actions>
        <Button @click="openAdd"><Plus class="h-4 w-4" /> Novo Abastecimento</Button>
      </template>
    </PageHeader>

    <!-- Resumo -->
    <div class="mb-6 grid grid-cols-2 gap-4 lg:grid-cols-4">
      <StatCard
        v-for="(s, i) in stats" :key="s.label"
        :label="s.label" :value="s.value" :icon="s.icon" :tone="s.tone"
        :highlight="s.highlight" :delay="0.05 + i * 0.05"
      />
    </div>

    <!-- Gráficos -->
    <div v-if="!loading && items.length" class="mb-6 grid grid-cols-1 gap-4 lg:grid-cols-2">
      <ChartCard title="Tipos de Custo" caption="Participação por combustível" :delay="0.25">
        <div class="flex h-full items-center gap-5">
          <div class="h-full min-w-0 flex-1"><Doughnut :data="byCostType" :options="pieOptions" /></div>
          <ChartLegend class="flex-1" :items="costTypeLegend" :total="totalValue" />
        </div>
      </ChartCard>
      <ChartCard title="Custo e Litros por Período" caption="Evolução mensal" :delay="0.3">
        <Bar :data="monthly" :options="monthlyOptions" />
      </ChartCard>
    </div>

    <!-- Filtros -->
    <FilterBar :has-active="hasFilters" :delay="0.32" @clear="clearFilters">
      <label class="block"><span class="mb-1 block text-xs font-medium text-muted-foreground">De</span>
        <input v-model="filters.from" type="date" class="ui-input" />
      </label>
      <label class="block"><span class="mb-1 block text-xs font-medium text-muted-foreground">Até</span>
        <input v-model="filters.to" type="date" class="ui-input" />
      </label>
      <label class="block"><span class="mb-1 block text-xs font-medium text-muted-foreground">Categoria</span>
        <select v-model="filters.category" class="ui-input">
          <option value="">Todas</option>
          <option v-for="c in categoryOptions" :key="c" :value="c">{{ c }}</option>
        </select>
      </label>
      <label class="block"><span class="mb-1 block text-xs font-medium text-muted-foreground">Custo</span>
        <select v-model="filters.costName" class="ui-input">
          <option value="">Todos</option>
          <option v-for="c in costNameOptions" :key="c" :value="c">{{ c }}</option>
        </select>
      </label>
      <label class="block"><span class="mb-1 block text-xs font-medium text-muted-foreground">Tipo de Custo</span>
        <select v-model="filters.costType" class="ui-input">
          <option value="">Todos</option>
          <option v-for="c in costTypeOptions" :key="c" :value="c">{{ c }}</option>
        </select>
      </label>
      <label class="block"><span class="mb-1 block text-xs font-medium text-muted-foreground">Placa</span>
        <select v-model="filters.plate" class="ui-input">
          <option value="">Todas</option>
          <option v-for="p in plateOptions" :key="p" :value="p">{{ p }}</option>
        </select>
      </label>
    </FilterBar>

    <!-- Tabela -->
    <div v-if="loading" class="flex justify-center py-20"><Spinner /></div>
    <div v-else class="a-in overflow-hidden rounded-xl border bg-card shadow-card" style="animation-delay: 0.38s">
      <div class="flex items-center justify-between border-b p-4">
        <div class="flex items-center gap-2">
          <Fuel class="h-4 w-4 text-warning" />
          <span class="text-sm font-bold uppercase tracking-wider">Lançamentos de Combustível</span>
          <Badge>{{ filtered.length }}</Badge>
        </div>
        <span class="text-sm font-semibold">{{ formatBRL(totalValue) }}</span>
      </div>

      <div class="scrollbar-brand overflow-x-auto">
        <table class="w-full text-sm">
          <thead class="bg-muted/50">
            <tr>
              <th class="th">Data</th>
              <th class="th">Veículo</th>
              <th class="th">Categoria</th>
              <th class="th">Tipo de Custo</th>
              <th class="th">Custo</th>
              <th class="th th-r">Litros</th>
              <th class="th th-r">Valor (R$)</th>
              <th class="th th-r">KM</th>
              <th class="th">Fornecedor</th>
              <th class="th th-r">Ações</th>
            </tr>
          </thead>
          <tbody>
            <tr v-if="paged.length === 0">
              <td colspan="10" class="py-12 text-center text-muted-foreground">Nenhum registro encontrado</td>
            </tr>
            <tr v-for="r in paged" :key="r.id" class="border-b transition-colors duration-200 hover:bg-primary/[0.06]">
              <!-- Data -->
              <td class="whitespace-nowrap px-4 py-2.5 font-medium">{{ formatDate(r.date) }}</td>
              <!-- Veículo -->
              <td class="whitespace-nowrap px-4 py-2.5">
                <div class="flex items-center gap-2">
                  <div class="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-muted">
                    <Car class="h-3.5 w-3.5 text-muted-foreground" />
                  </div>
                  <div class="leading-tight">
                    <p class="text-sm font-bold tracking-widest">{{ r.plate }}</p>
                    <p v-if="r.vehicle_model || vehByPlate[r.plate]?.vehicle_model" class="text-xs text-muted-foreground">
                      {{ r.vehicle_model || vehByPlate[r.plate]?.vehicle_model }}
                    </p>
                  </div>
                </div>
              </td>
              <!-- Categoria -->
              <td class="px-4 py-2.5"><Badge>{{ catOf(r) || "—" }}</Badge></td>
              <!-- Tipo de Custo -->
              <td class="px-4 py-2.5">
                <span class="inline-flex items-center gap-1.5 rounded-full border bg-muted/40 px-2.5 py-1 text-xs font-semibold">
                  <span class="h-1.5 w-1.5 rounded-full" :style="{ background: typeColor(r.cost_type) }" />
                  {{ r.cost_type }}
                </span>
              </td>
              <!-- Custo -->
              <td class="px-4 py-2.5"><Badge tone="bg-warning/10 text-warning border-warning/20">{{ r.cost_name }}</Badge></td>
              <!-- Litros -->
              <td class="px-4 py-2.5 text-right tabular-nums">{{ num(Number(r.quantity), 2) }}</td>
              <!-- Valor -->
              <td class="px-4 py-2.5 text-right font-semibold text-success tabular-nums">{{ formatBRL(r.total_value) }}</td>
              <!-- KM -->
              <td class="px-4 py-2.5 text-right tabular-nums text-muted-foreground">{{ r.km ? num(Number(r.km)) : "—" }}</td>
              <!-- Fornecedor -->
              <td class="px-4 py-2.5">
                <div class="max-w-[180px] leading-tight">
                  <p class="truncate text-xs font-medium" :title="r.supplier ?? ''">{{ r.supplier || "—" }}</p>
                  <p v-if="r.invoice_number" class="text-xs text-muted-foreground">Nota: {{ r.invoice_number }}</p>
                </div>
              </td>
              <!-- Ações -->
              <td class="px-4 py-2.5">
                <div class="flex items-center justify-end gap-1">
                  <button class="rounded-lg p-1.5 text-muted-foreground transition-colors hover:bg-muted hover:text-foreground" @click="openEdit(r)">
                    <Pencil class="h-3.5 w-3.5" />
                  </button>
                  <button class="rounded-lg p-1.5 text-muted-foreground transition-colors hover:bg-destructive/10 hover:text-destructive" @click="deleteId = r.id">
                    <Trash2 class="h-3.5 w-3.5" />
                  </button>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <!-- Rodapé + paginação -->
      <div class="flex flex-col items-center justify-between gap-3 border-t bg-muted/30 px-4 py-2.5 sm:flex-row">
        <span class="text-xs text-muted-foreground">{{ filtered.length }} de {{ items.length }} registro(s)</span>
        <div v-if="totalPages > 1" class="flex items-center gap-1">
          <button class="pg" :disabled="page === 1" @click="page = 1">«</button>
          <button class="pg" :disabled="page === 1" @click="page--">‹</button>
          <template v-for="(p, i) in pageNumbers" :key="i">
            <span v-if="p === '...'" class="px-1.5 text-xs text-muted-foreground">…</span>
            <button v-else class="pg" :class="p === page && 'border-primary bg-primary text-primary-foreground'" @click="page = (p as number)">{{ p }}</button>
          </template>
          <button class="pg" :disabled="page === totalPages" @click="page++">›</button>
          <button class="pg" :disabled="page === totalPages" @click="page = totalPages">»</button>
        </div>
      </div>
    </div>

    <!-- Formulário -->
    <Modal :open="dialogOpen" :title="editing ? 'Editar Abastecimento' : 'Novo Abastecimento'" :saving="saving" @close="dialogOpen = false" @submit="submit">
      <div class="grid grid-cols-2 gap-3">
        <FormField label="Data" required><input v-model="form.date" type="date" class="ui-input" /></FormField>
        <FormField label="Veículo (Placa)" required>
          <select v-model="form.plate" class="ui-input">
            <option value="">Selecione...</option>
            <option v-for="v in vehicleList" :key="v.id" :value="v.plate">{{ v.plate }} — {{ v.vehicle_model }}</option>
          </select>
        </FormField>
        <FormField label="Tipo de Custo" required class="col-span-2">
          <select v-model="selectedCostTypeId" class="ui-input" @change="selectCostType(selectedCostTypeId)">
            <option value="">Selecione...</option>
            <option v-for="c in costTypes" :key="c.id" :value="c.id">{{ c.cost_name }} — {{ c.cost_type }}</option>
          </select>
        </FormField>
        <FormField label="Quantidade" required><input v-model.number="form.quantity" type="number" step="0.001" class="ui-input" /></FormField>
        <FormField label="Unidade">
          <select v-model="form.unit" class="ui-input"><option>LT</option><option>UN</option></select>
        </FormField>
        <FormField label="Valor Total (R$)" required><input v-model.number="form.total_value" type="number" step="0.01" class="ui-input" /></FormField>
        <FormField label="KM"><input v-model.number="form.km" type="number" class="ui-input" /></FormField>
        <FormField label="Fornecedor" class="col-span-2"><input v-model="form.supplier" class="ui-input" /></FormField>
        <FormField label="Nota Fiscal"><input v-model="form.invoice_number" class="ui-input" /></FormField>
        <FormField label="Observação" class="col-span-2"><input v-model="form.observation" class="ui-input" /></FormField>
      </div>
    </Modal>

    <!-- Confirmar exclusão -->
    <Modal :open="!!deleteId" title="Confirmar exclusão" submit-label="Excluir" @close="deleteId = null" @submit="confirmDelete">
      <p class="text-sm text-muted-foreground">Tem certeza que deseja excluir este lançamento? Esta ação não poderá ser desfeita.</p>
    </Modal>
  </div>
</template>

<style scoped>
.th {
  @apply px-4 py-2.5 text-left text-xs font-semibold uppercase tracking-wider text-muted-foreground;
}
.th-r {
  @apply text-right;
}
.pg {
  @apply flex h-7 min-w-[1.75rem] items-center justify-center rounded-md border bg-card px-1.5 text-xs font-medium transition-colors hover:bg-muted disabled:cursor-not-allowed disabled:opacity-40;
}
</style>
