// src/pages/Home.jsx
import React, { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { useQuery } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { Fuel, Wrench, DollarSign, Truck, BarChart2, Settings, Bell } from 'lucide-react';

const modules = [
  {
    label: 'Abastecimento',
    path: '/abastecimentos',
    bg: 'from-teal-600 to-emerald-700',
    iconBg: 'bg-teal-500/30',
    emoji: '⛽',
    icon: Fuel,
  },
  {
    label: 'Manutenção',
    path: '/manutencao',
    bg: 'from-blue-600 to-blue-800',
    iconBg: 'bg-blue-500/30',
    emoji: '🔧',
    icon: Wrench,
  },
  {
    label: 'Custos Operacionais',
    path: '/custos-operacionais',
    bg: 'from-orange-500 to-amber-600',
    iconBg: 'bg-orange-400/30',
    emoji: '💰',
    icon: DollarSign,
  },
  {
    label: 'Analise',
    path: '/analises',
    bg: 'from-violet-600 to-purple-800',
    iconBg: 'bg-violet-500/30',
    emoji: '📊',
    icon: BarChart2,
  },
  {
    label: 'Configurações',
    path: '/parametrizacoes',
    bg: 'from-cyan-600 to-teal-700',
    iconBg: 'bg-cyan-500/30',
    emoji: '⚙️',
    icon: Settings,
  },
];

const fmtCurrency = (v) =>
  new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(v || 0);
const fmtNum = (v) => new Intl.NumberFormat('pt-BR').format(v || 0);

const last30Days = () => {
  const d = new Date();
  d.setDate(d.getDate() - 30);
  return d.toISOString().split('T')[0];
};

export default function Home() {
  const [period, setPeriod] = React.useState('30d');
  const since = period === '30d' ? last30Days() : null;

  const { data: fuelRecords = [] } = useQuery({
    queryKey: ['home-fuel'],
    queryFn: () => base44.entities.FuelRecord.list('-date', 2000),
  });
  const { data: maintenanceRecords = [] } = useQuery({
    queryKey: ['home-maint'],
    queryFn: () => base44.entities.MaintenanceRecord.list('-date', 2000),
  });
  const { data: operationalRecords = [] } = useQuery({
    queryKey: ['home-op'],
    queryFn: () => base44.entities.OperationalCostRecord.list('-date', 2000),
  });
  const { data: vehicles = [] } = useQuery({
    queryKey: ['home-vehicles'],
    queryFn: () => base44.entities.Vehicle.list(),
  });

  const kpis = useMemo(() => {
    const maint30 = since ? maintenanceRecords.filter(r => r.date >= since) : maintenanceRecords;
    const op30 = since ? operationalRecords.filter(r => r.date >= since) : operationalRecords;

    const totalAbastecido = fuelRecords.reduce((s, r) => s + (r.quantity || 0), 0);
    const custoOperacional = op30.reduce((s, r) => s + (r.total_value || 0), 0);
    const totalManutencoes = maint30.length;
    const custoManutencoes = maint30.reduce((s, r) => s + (r.total_value || 0), 0);
    const activeVehicles = vehicles.filter(v => v.is_active !== false).length || vehicles.length;

    return { totalAbastecido, custoOperacional, totalManutencoes, custoManutencoes, activeVehicles };
  }, [fuelRecords, maintenanceRecords, operationalRecords, vehicles, since]);

  const now = new Date();
  const greeting = now.getHours() < 12 ? 'Bom dia' : now.getHours() < 18 ? 'Boa tarde' : 'Boa noite';

  return (
    <div className="min-h-screen bg-[#0d1b2a] text-white">

      {/* Top bar */}
      <div className="flex items-center justify-between px-6 py-4 border-b border-white/5">
        <motion.div
          initial={{ opacity: 0, x: -16 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.4 }}
        >
          <h1 className="text-xl font-bold text-white">{greeting}, bem-vindo!</h1>
          <p className="text-xs text-white/40 mt-0.5">
            {now.toLocaleDateString('pt-BR', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })}
          </p>
        </motion.div>
        <button className="relative p-2 rounded-xl bg-white/5 hover:bg-white/10 transition-colors">
          <Bell className="w-5 h-5 text-white/60" />
        </button>
      </div>

      <div className="px-6 py-8 space-y-8">

        {/* Module Cards */}
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.45 }}
        >
          <div className="flex gap-4 overflow-x-auto pb-2 scrollbar-hide">
            {modules.map((mod, i) => {
              const Icon = mod.icon;
              return (
                <motion.div
                  key={mod.label}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: i * 0.07, duration: 0.4 }}
                  className="shrink-0"
                >
                  <Link to={mod.path}>
                    <div className={`relative w-44 h-44 rounded-2xl bg-gradient-to-br ${mod.bg} flex flex-col items-center justify-center gap-3 shadow-lg hover:scale-105 hover:shadow-2xl transition-all duration-200 cursor-pointer overflow-hidden`}>
                      {/* Glow circle */}
                      <div className={`w-20 h-20 rounded-full ${mod.iconBg} flex items-center justify-center`}>
                        <Icon className="w-10 h-10 text-white drop-shadow-lg" />
                      </div>
                      <span className="text-sm font-bold text-white text-center leading-tight px-2">
                        {mod.label}
                      </span>
                      {/* Bottom indicator */}
                      <div className="absolute bottom-0 left-0 right-0 h-1 bg-white/20 rounded-b-2xl" />
                    </div>
                  </Link>
                </motion.div>
              );
            })}
          </div>
        </motion.div>

        {/* Resumo da Frota */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3, duration: 0.45 }}
          className="bg-[#152032] rounded-2xl border border-white/5 p-6"
        >
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-base font-bold text-white">Resumo da Frota</h2>
            <select
              value={period}
              onChange={e => setPeriod(e.target.value)}
              className="bg-white/5 border border-white/10 rounded-lg px-3 py-1.5 text-xs font-semibold text-white/80 outline-none cursor-pointer"
            >
              <option value="30d" className="bg-[#152032]">Últimos 30 dias</option>
              <option value="all" className="bg-[#152032]">Período todo</option>
            </select>
          </div>

          <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
            {/* Total Veículos */}
            <div className="flex items-center gap-3 bg-white/5 rounded-xl p-4">
              <div className="w-10 h-10 rounded-full bg-blue-500/20 flex items-center justify-center shrink-0">
                <Truck className="w-5 h-5 text-blue-400" />
              </div>
              <div>
                <p className="text-xl font-extrabold text-white leading-none">{fmtNum(kpis.activeVehicles)}</p>
                <p className="text-xs font-semibold text-white/60 mt-0.5">Total de Veículos</p>
                <p className="text-[10px] text-white/30">Ativos na frota</p>
              </div>
            </div>

            {/* Total Abastecido */}
            <div className="flex items-center gap-3 bg-white/5 rounded-xl p-4">
              <div className="w-10 h-10 rounded-full bg-emerald-500/20 flex items-center justify-center shrink-0">
                <Fuel className="w-5 h-5 text-emerald-400" />
              </div>
              <div>
                <p className="text-xl font-extrabold text-white leading-none">{fmtNum(Math.round(kpis.totalAbastecido))} L</p>
                <p className="text-xs font-semibold text-white/60 mt-0.5">Total Abastecido</p>
                <p className="text-[10px] text-white/30">Acumulado geral</p>
              </div>
            </div>

            {/* Custo Operacional */}
            <div className="flex items-center gap-3 bg-white/5 rounded-xl p-4">
              <div className="w-10 h-10 rounded-full bg-orange-500/20 flex items-center justify-center shrink-0">
                <DollarSign className="w-5 h-5 text-orange-400" />
              </div>
              <div>
                <p className="text-lg font-extrabold text-white leading-none">{fmtCurrency(kpis.custoOperacional)}</p>
                <p className="text-xs font-semibold text-white/60 mt-0.5">Custo Operacional</p>
                <p className="text-[10px] text-white/30">No período</p>
              </div>
            </div>

            {/* Manutenções */}
            <Link to="/analises?tab=manutencao" className="flex items-center gap-3 bg-white/5 rounded-xl p-4 hover:bg-white/10 transition-colors group">
              <div className="w-10 h-10 rounded-full bg-violet-500/20 flex items-center justify-center shrink-0">
                <Wrench className="w-5 h-5 text-violet-400" />
              </div>
              <div>
                <p className="text-lg font-extrabold text-white leading-none">{fmtCurrency(kpis.custoManutencoes)}</p>
                <p className="text-xs font-semibold text-white/60 mt-0.5">Manutenções</p>
                <p className="text-[10px] text-violet-400/70 group-hover:text-violet-300 transition-colors">Ver análises →</p>
              </div>
            </Link>
          </div>
        </motion.div>

        {/* Banner / Trucks visual */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.45, duration: 0.45 }}
          className="relative overflow-hidden rounded-2xl bg-gradient-to-r from-[#0e2a4a] via-[#0d3a6a] to-[#0a2240] border border-white/5 p-6 min-h-[120px]"
        >
          <div className="absolute inset-0 opacity-10"
            style={{
              backgroundImage: `radial-gradient(circle at 70% 50%, #3b82f6 0%, transparent 60%)`,
            }}
          />
          <div className="relative z-10 flex items-center justify-between">
            <div>
              <h3 className="text-lg font-bold text-white">Gestão Completa da sua Frota</h3>
              <p className="text-sm text-white/50 mt-1">Monitore, analise e otimize seus custos em tempo real</p>
              <Link
                to="/analises"
                className="inline-flex items-center gap-2 mt-3 bg-blue-600 hover:bg-blue-500 text-white text-xs font-semibold px-4 py-2 rounded-lg transition-colors"
              >
                <BarChart2 className="w-4 h-4" />
                Ver Análises
              </Link>
            </div>
            <div className="hidden md:flex gap-3 opacity-60">
              <div className="text-6xl">🚛</div>
              <div className="text-5xl self-end">🚐</div>
            </div>
          </div>
        </motion.div>

      </div>
    </div>
  );
}

// frontend-vue/src/pages/Home.vue
<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { RouterLink } from "vue-router";
import { Fuel, Wrench, DollarSign, Truck, BarChart2, Settings, Bell } from "lucide-vue-next";
import { vehicles, fuelRecords, maintenanceRecords, operationalCostRecords } from "@/services/api";
import { formatBRL, formatNum } from "@/lib/utils";
import Spinner from "@/components/ui/Spinner.vue";

const modules = [
  { label: "Abastecimento", path: "/abastecimentos", icon: Fuel },
  { label: "Manutenção", path: "/manutencao", icon: Wrench },
  { label: "Custos Operacionais", path: "/custos-operacionais", icon: DollarSign },
  { label: "Análise", path: "/analises", icon: BarChart2 },
  { label: "Configurações", path: "/parametrizacoes", icon: Settings },
];

const loading = ref(true);
const fuel = ref<any[]>([]);
const maint = ref<any[]>([]);
const oper = ref<any[]>([]);
const fleet = ref<any[]>([]);
const period = ref<"30d" | "all">("30d");

onMounted(async () => {
  try {
    [fuel.value, maint.value, oper.value, fleet.value] = await Promise.all([
      fuelRecords.list({ limit: 10000 }),
      maintenanceRecords.list({ limit: 10000 }),
      operationalCostRecords.list({ limit: 10000 }),
      vehicles.list({ limit: 1000 }),
    ]);
  } finally {
    loading.value = false;
  }
});

const since = computed(() => {
  if (period.value === "all") return null;
  const d = new Date();
  d.setDate(d.getDate() - 30);
  return d.toISOString().slice(0, 10);
});
const inPeriod = (arr: any[]) => (since.value ? arr.filter((r) => (r.date ?? "") >= since.value!) : arr);

const kpis = computed(() => {
  const maintP = inPeriod(maint.value);
  const opP = inPeriod(oper.value);
  return {
    activeVehicles: fleet.value.filter((v) => v.is_active !== false).length,
    totalAbastecido: fuel.value.reduce((s, r) => s + Number(r.quantity || 0), 0),
    custoOperacional: opP.reduce((s, r) => s + Number(r.total_value || 0), 0),
    custoManutencoes: maintP.reduce((s, r) => s + Number(r.total_value || 0), 0),
  };
});

const now = new Date();
const greeting = now.getHours() < 12 ? "Bom dia" : now.getHours() < 18 ? "Boa tarde" : "Boa noite";
const dateLabel = now.toLocaleDateString("pt-BR", { weekday: "long", day: "numeric", month: "long", year: "numeric" });
</script>

<template>
  <div class="w-full">
    <!-- Top bar -->
    <div class="a-in flex items-center justify-between border-b p-6">
      <div>
        <h1 class="text-xl font-bold text-foreground">{{ greeting }}, bem-vindo!</h1>
        <p class="mt-0.5 text-xs capitalize text-muted-foreground">{{ dateLabel }}</p>
      </div>
      <button class="rounded-xl border bg-card p-2.5 text-muted-foreground transition-colors hover:bg-muted hover:text-foreground">
        <Bell class="h-5 w-5" />
      </button>
    </div>

    <div class="space-y-8 p-6 md:p-8">
      <!-- Cards de atalho -->
      <div class="scrollbar-brand flex gap-4 overflow-x-auto pb-2">
        <RouterLink
          v-for="(m, i) in modules"
          :key="m.label"
          :to="m.path"
          class="a-in group relative flex h-44 w-44 shrink-0 flex-col items-center justify-center gap-3 overflow-hidden rounded-xl border bg-card shadow-card transition-all duration-200 hover:-translate-y-1 hover:border-primary/60 hover:shadow-card-md"
          :style="{ animationDelay: `${i * 0.06}s` }"
        >
          <div class="flex h-20 w-20 items-center justify-center rounded-2xl bg-primary/15 text-primary-hover transition-colors duration-200 group-hover:bg-primary group-hover:text-primary-foreground">
            <component :is="m.icon" class="h-10 w-10" />
          </div>
          <span class="px-2 text-center text-sm font-bold leading-tight text-foreground">{{ m.label }}</span>
          <span class="absolute inset-x-4 bottom-0 h-0.5 rounded-full bg-primary opacity-0 transition-opacity duration-200 group-hover:opacity-100" />
        </RouterLink>
      </div>

      <!-- Resumo da Frota -->
      <div class="a-in rounded-xl border bg-card p-6 shadow-card" style="animation-delay: 0.28s">
        <div class="mb-6 flex items-center justify-between">
          <h2 class="text-base font-bold text-foreground">Resumo da Frota</h2>
          <select v-model="period" class="ui-input h-9 w-auto">
            <option value="30d">Últimos 30 dias</option>
            <option value="all">Período todo</option>
          </select>
        </div>

        <div v-if="loading" class="flex justify-center py-8"><Spinner /></div>
        <div v-else class="grid grid-cols-2 gap-4 lg:grid-cols-4">
          <div class="flex items-center gap-3 rounded-xl border bg-muted/30 p-4">
            <div class="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-info/15 text-info"><Truck class="h-5 w-5" /></div>
            <div>
              <p class="text-xl font-extrabold leading-none text-foreground">{{ formatNum(kpis.activeVehicles) }}</p>
              <p class="mt-0.5 text-xs font-semibold text-muted-foreground">Total de Veículos</p>
              <p class="text-[10px] text-muted-foreground/70">Ativos na frota</p>
            </div>
          </div>
          <div class="flex items-center gap-3 rounded-xl border bg-muted/30 p-4">
            <div class="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-success/15 text-success"><Fuel class="h-5 w-5" /></div>
            <div>
              <p class="text-xl font-extrabold leading-none text-foreground">{{ formatNum(Math.round(kpis.totalAbastecido)) }} L</p>
              <p class="mt-0.5 text-xs font-semibold text-muted-foreground">Total Abastecido</p>
              <p class="text-[10px] text-muted-foreground/70">Acumulado geral</p>
            </div>
          </div>
          <div class="flex items-center gap-3 rounded-xl border bg-muted/30 p-4">
            <div class="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-warning/15 text-warning"><DollarSign class="h-5 w-5" /></div>
            <div>
              <p class="text-lg font-extrabold leading-none text-foreground">{{ formatBRL(kpis.custoOperacional) }}</p>
              <p class="mt-0.5 text-xs font-semibold text-muted-foreground">Custo Operacional</p>
              <p class="text-[10px] text-muted-foreground/70">No período</p>
            </div>
          </div>
          <RouterLink to="/analises?tab=manutencao" class="group flex items-center gap-3 rounded-xl border bg-muted/30 p-4 transition-colors hover:bg-muted/60">
            <div class="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-destructive/15 text-destructive"><Wrench class="h-5 w-5" /></div>
            <div>
              <p class="text-lg font-extrabold leading-none text-foreground">{{ formatBRL(kpis.custoManutencoes) }}</p>
              <p class="mt-0.5 text-xs font-semibold text-muted-foreground">Manutenções</p>
              <p class="text-[10px] font-semibold text-primary-hover">Ver análises →</p>
            </div>
          </RouterLink>
        </div>
      </div>

      <!-- Banner CTA -->
      <div class="a-in relative overflow-hidden rounded-xl border bg-gradient-to-r from-accent to-accent/80 p-6" style="animation-delay: 0.4s">
        <div class="pointer-events-none absolute right-10 top-1/2 h-64 w-64 -translate-y-1/2 rounded-full bg-primary/20 blur-3xl" />
        <div class="relative z-10 flex items-center justify-between">
          <div>
            <h3 class="text-lg font-bold text-accent-foreground">Gestão Completa da sua Frota</h3>
            <p class="mt-1 text-sm text-accent-foreground/70">Monitore, analise e otimize seus custos em tempo real</p>
            <RouterLink
              to="/analises"
              class="mt-3 inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-xs font-semibold text-primary-foreground transition-all duration-200 hover:bg-primary-hover hover:shadow-glow"
            >
              <BarChart2 class="h-4 w-4" /> Ver Análises
            </RouterLink>
          </div>
          <div class="hidden gap-3 text-6xl opacity-70 md:flex">
            <span>🚛</span><span class="self-end text-5xl">🚐</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
