// frontend-vue/src/components/ui/DataTable.vue
<script setup lang="ts" generic="T extends { id: string }">
import { computed, ref } from "vue";
import { Pencil, Trash2, Search } from "lucide-vue-next";
import Button from "./Button.vue";
import Modal from "./Modal.vue";

interface Column {
  key: string;
  label: string;
  class?: string;
}

const props = withDefaults(
  defineProps<{
    columns: Column[];
    data: T[];
    searchPlaceholder?: string;
    emptyMessage?: string;
    editable?: boolean;
    deletable?: boolean;
  }>(),
  {
    searchPlaceholder: "Buscar...",
    emptyMessage: "Nenhum registro encontrado",
    editable: true,
    deletable: true,
  },
);

const emit = defineEmits<{ edit: [row: T]; delete: [id: string] }>();

const search = ref("");
const deleteId = ref<string | null>(null);

const filtered = computed(() => {
  const q = search.value.toLowerCase().trim();
  if (!q) return props.data;
  return props.data.filter((row) =>
    props.columns.some((col) => {
      const val = (row as any)[col.key];
      return val != null && String(val).toLowerCase().includes(q);
    }),
  );
});

function confirmDelete() {
  if (deleteId.value) emit("delete", deleteId.value);
  deleteId.value = null;
}
</script>

<template>
  <div class="a-in overflow-hidden rounded-xl border bg-card shadow-card" style="animation-delay: 0.15s">
    <div class="flex items-center justify-between gap-4 border-b p-4">
      <div class="relative max-w-sm flex-1">
        <Search class="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
        <input v-model="search" :placeholder="searchPlaceholder" class="ui-input pl-9" />
      </div>
      <slot name="toolbar" />
    </div>

    <div class="scrollbar-brand overflow-x-auto">
      <table class="w-full text-sm">
        <thead>
          <tr class="bg-muted/50">
            <th
              v-for="col in columns"
              :key="col.key"
              class="px-4 py-2.5 text-left text-xs font-semibold uppercase tracking-wider text-muted-foreground"
            >
              {{ col.label }}
            </th>
            <th
              v-if="editable || deletable"
              class="w-24 px-4 py-2.5 text-right text-xs font-semibold uppercase tracking-wider text-muted-foreground"
            >
              Ações
            </th>
          </tr>
        </thead>
        <tbody>
          <tr v-if="filtered.length === 0">
            <td :colspan="columns.length + 1" class="py-12 text-center text-muted-foreground">
              {{ emptyMessage }}
            </td>
          </tr>
          <tr
            v-for="row in filtered"
            :key="row.id"
            class="border-b transition-colors duration-200 hover:bg-primary/[0.06]"
          >
            <td v-for="col in columns" :key="col.key" :class="['px-4 py-2.5', col.class]">
              <slot :name="`cell-${col.key}`" :row="row" :value="(row as any)[col.key]">
                {{ (row as any)[col.key] ?? "—" }}
              </slot>
            </td>
            <td v-if="editable || deletable" class="px-4 py-2.5 text-right">
              <div class="flex items-center justify-end gap-1">
                <Button v-if="editable" variant="ghost" size="icon" @click="emit('edit', row)">
                  <Pencil class="h-3.5 w-3.5" />
                </Button>
                <Button
                  v-if="deletable"
                  variant="ghost"
                  size="icon"
                  @click="deleteId = row.id"
                >
                  <Trash2 class="h-3.5 w-3.5 text-destructive" />
                </Button>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="border-t bg-muted/30 px-4 py-2.5 text-xs text-muted-foreground">
      {{ filtered.length }} de {{ data.length }} registro(s)
    </div>

    <Modal
      :open="!!deleteId"
      title="Confirmar exclusão"
      submit-label="Excluir"
      @close="deleteId = null"
      @submit="confirmDelete"
    >
      <p class="text-sm text-muted-foreground">
        Tem certeza que deseja excluir este registro? Esta ação não poderá ser desfeita.
      </p>
    </Modal>
  </div>
</template>

// src/components/shared/DataTable.jsx
import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Card } from '@/components/ui/card';
import { Pencil, Trash2, Search, Plus } from 'lucide-react';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle } from
'@/components/ui/alert-dialog';

export default function DataTable({
  columns,
  data,
  onEdit,
  onDelete,
  onAdd,
  addLabel = "Adicionar",
  searchPlaceholder = "Buscar...",
  emptyMessage = "Nenhum registro encontrado"
}) {
  const [search, setSearch] = useState('');
  const [deleteId, setDeleteId] = useState(null);

  const filteredData = data.filter((row) =>
  columns.some((col) => {
    const val = row[col.key];
    return val && String(val).toLowerCase().includes(search.toLowerCase());
  })
  );

  return (
    <Card className="overflow-hidden border shadow-sm">
      {/* Toolbar */}
      <div className="flex items-center justify-between gap-4 p-4 border-b bg-card">
        <div className="relative flex-1 max-w-sm">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
          <Input
            placeholder={searchPlaceholder}
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="pl-9 bg-background" />
          
        </div>
        {onAdd &&
        <Button onClick={onAdd} className="gap-2 bg-primary hover:bg-primary/90 shadow-md shadow-primary/20">
            <Plus className="w-4 h-4" />
            {addLabel}
          </Button>
        }
      </div>

      {/* Table */}
      <div className="overflow-x-auto">
        <Table className="opacity-100">
          <TableHeader>
            <TableRow className="bg-muted/50">
              {columns.map((col) =>
              <TableHead key={col.key} className="font-semibold text-xs uppercase tracking-wider text-muted-foreground">
                  {col.label}
                </TableHead>
              )}
              {(onEdit || onDelete) &&
              <TableHead className="text-right font-semibold text-xs uppercase tracking-wider text-muted-foreground w-28">
                  Ações
                </TableHead>
              }
            </TableRow>
          </TableHeader>
          <TableBody>
            <AnimatePresence>
              {filteredData.length === 0 ?
              <TableRow>
                  <TableCell colSpan={columns.length + 1} className="text-center py-12 text-muted-foreground">
                    {emptyMessage}
                  </TableCell>
                </TableRow> :

              filteredData.map((row, idx) =>
              <motion.tr
                key={row.id}
                initial={{ opacity: 0, y: 5 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -5 }}
                transition={{ delay: idx * 0.02 }}
                className="border-b hover:bg-muted/30 transition-colors">
                
                    {columns.map((col) =>
                <TableCell key={col.key} className="py-3">
                        {col.render ? col.render(row[col.key], row) : row[col.key]}
                      </TableCell>
                )}
                    {(onEdit || onDelete) &&
                <TableCell className="text-right py-3">
                        <div className="flex items-center justify-end gap-1">
                          {onEdit &&
                    <Button variant="ghost" size="icon" className="h-8 w-8 text-muted-foreground hover:text-primary" onClick={() => onEdit(row)}>
                              <Pencil className="w-3.5 h-3.5" />
                            </Button>
                    }
                          {onDelete &&
                    <Button variant="ghost" size="icon" className="h-8 w-8 text-muted-foreground hover:text-destructive" onClick={() => setDeleteId(row.id)}>
                              <Trash2 className="w-3.5 h-3.5" />
                            </Button>
                    }
                        </div>
                      </TableCell>
                }
                  </motion.tr>
              )
              }
            </AnimatePresence>
          </TableBody>
        </Table>
      </div>

      {/* Stats */}
      <div className="px-4 py-2.5 bg-muted/30 border-t text-xs text-muted-foreground">
        {filteredData.length} de {data.length} registro(s)
      </div>

      {/* Delete Dialog */}
      <AlertDialog open={!!deleteId} onOpenChange={() => setDeleteId(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Confirmar exclusão</AlertDialogTitle>
            <AlertDialogDescription>
              Tem certeza que deseja excluir este registro? Esta ação não poderá ser desfeita.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancelar</AlertDialogCancel>
            <AlertDialogAction
              className="bg-destructive hover:bg-destructive/90"
              onClick={() => {
                onDelete(deleteId);
                setDeleteId(null);
              }}>
              
              Excluir
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </Card>);

}
