// frontend-vue/src/components/ui/PageHeader.vue
<script setup lang="ts">
import type { Component } from "vue";

defineProps<{
  title: string;
  subtitle?: string;
  icon?: Component;
  /** Sobrescreve a caixa do ícone; padrão = marca F8 (amarelo/preto). */
  iconClass?: string;
}>();
</script>

<template>
  <div class="a-in mb-8 flex items-center gap-4">
    <div
      v-if="icon"
      class="flex h-11 w-11 items-center justify-center rounded-lg shadow-glow"
      :class="iconClass ?? 'bg-primary text-primary-foreground'"
    >
      <component :is="icon" class="h-5 w-5" />
    </div>
    <div>
      <h1 class="text-2xl font-bold tracking-tight text-foreground">{{ title }}</h1>
      <p v-if="subtitle" class="mt-0.5 text-xs uppercase tracking-widest text-muted-foreground">
        {{ subtitle }}
      </p>
    </div>
    <div class="ml-auto"><slot name="actions" /></div>
  </div>
</template>

// src/components/shared/PageHeader.jsx
import React from 'react';
import { motion } from 'framer-motion';
import { ChevronRight } from 'lucide-react';
import { Link } from 'react-router-dom';

export default function PageHeader({ title, subtitle, icon: Icon, iconColor, breadcrumbs }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: -10 }}
      animate={{ opacity: 1, y: 0 }}
      className="mb-8"
    >
      {breadcrumbs && (
        <div className="flex items-center gap-1.5 text-sm text-muted-foreground mb-3">
          {breadcrumbs.map((crumb, i) => (
            <React.Fragment key={i}>
              {i > 0 && <ChevronRight className="w-3.5 h-3.5" />}
              {crumb.path ? (
                <Link to={crumb.path} className="hover:text-foreground transition-colors">
                  {crumb.label}
                </Link>
              ) : (
                <span className="text-foreground font-medium">{crumb.label}</span>
              )}
            </React.Fragment>
          ))}
        </div>
      )}
      <div className="flex items-center gap-4">
        {Icon && (
          <div className={`w-12 h-12 rounded-2xl ${iconColor || 'bg-primary/10'} flex items-center justify-center`}>
            <Icon className={`w-6 h-6 ${iconColor ? iconColor.replace('bg-', 'text-').replace('/10', '') : 'text-primary'}`} />
          </div>
        )}
        <div>
          <h1 className="text-2xl font-bold text-foreground">{title}</h1>
          {subtitle && <p className="text-sm text-muted-foreground mt-0.5">{subtitle}</p>}
        </div>
      </div>
    </motion.div>
  );
}
