// frontend-vue/src/pages/CustosOperacionais.vue
<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from "vue";
import { DollarSign, Plus, ClipboardList, CalendarDays, TrendingUp, Car, Pencil, Trash2 } from "lucide-vue-next";
import { toast } from "vue-sonner";
import { Doughnut, Line } from "vue-chartjs";
import {
  operationalCostRecords, operationalCosts, vehicles,
  type OperationalCostRecord, type OperationalCost, type Vehicle,
} from "@/services/api";
import { useResource } from "@/composables/useResource";
import { formatBRL, formatDate } from "@/lib/utils";
import { seriesColors, palette, baseOptions, brlTick } from "@/lib/charts";
import PageHeader from "@/components/ui/PageHeader.vue";
import Modal from "@/components/ui/Modal.vue";
import Button from "@/components/ui/Button.vue";
import Badge from "@/components/ui/Badge.vue";
import StatCard from "@/components/ui/StatCard.vue";
import ChartCard from "@/components/ui/ChartCard.vue";
import ChartLegend from "@/components/ui/ChartLegend.vue";
import FilterBar from "@/components/ui/FilterBar.vue";
import FormField from "@/components/ui/FormField.vue";
import Spinner from "@/components/ui/Spinner.vue";

const { items, loading, saving, fetchAll, create, update, remove } =
  useResource<OperationalCostRecord>(operationalCostRecords, {
    created: "Custo lançado!", updated: "Custo atualizado!", removed: "Lançamento excluído!",
  });
const costList = ref<OperationalCost[]>([]);
const vehicleList = ref<Vehicle[]>([]);

onMounted(async () => {
  await Promise.all([
    fetchAll(),
    operationalCosts.list({ limit: 1000 }).then((c) => (costList.value = c)),
    vehicles.list({ limit: 1000 }).then((v) => (vehicleList.value = v)),
  ]);
});

const vehByPlate = computed(() => {
  const m: Record<string, Vehicle> = {};
  for (const v of vehicleList.value) if (v.plate) m[v.plate] = v;
  return m;
});

/* ---------- filtros ---------- */
const filters = reactive({ from: "", to: "", costName: "", plate: "" });
const filtered = computed(() =>
  items.value
    .filter((r) => {
      if (filters.from && (r.date ?? "") < filters.from) return false;
      if (filters.to && (r.date ?? "") > filters.to) return false;
      if (filters.costName && r.cost_name !== filters.costName) return false;
      if (filters.plate && r.plate !== filters.plate) return false;
      return true;
    })
    // Mais recentes primeiro.
    .sort((a, b) => (b.date ?? "").localeCompare(a.date ?? "")),
);
const hasFilters = computed(() => Object.values(filters).some(Boolean));
function clearFilters() {
  filters.from = filters.to = filters.costName = filters.plate = "";
}

const uniqSorted = (arr: (string | undefined | null)[]) =>
  [...new Set(arr.filter(Boolean) as string[])].sort((a, b) => a.localeCompare(b));
const costNameOptions = computed(() => uniqSorted(items.value.map((r) => r.cost_name)));
const plateOptions = computed(() => uniqSorted(items.value.map((r) => r.plate)));

/* ---------- resumo (reflete os filtros) ---------- */
const total = computed(() => filtered.value.reduce((s, r) => s + Number(r.total_value || 0), 0));
const avgDaily = computed(() => {
  const dates = filtered.value.map((r) => r.date).filter(Boolean).sort();
  if (dates.length < 2) return total.value;
  const d1 = new Date(dates[0] + "T12:00:00").getTime();
  const d2 = new Date(dates[dates.length - 1] + "T12:00:00").getTime();
  const days = Math.max(1, Math.round((d2 - d1) / 86400000));
  return total.value / days;
});
const avgMonthly = computed(() => {
  const months = new Set(filtered.value.map((r) => r.date?.slice(0, 7)).filter(Boolean));
  return months.size > 0 ? total.value / months.size : total.value;
});

const stats = computed(() => [
  { label: "Custo Total", value: formatBRL(total.value), sub: `${filtered.value.length} lançamentos`, icon: DollarSign, tone: "bg-primary/15 text-primary-hover", highlight: true },
  { label: "Lançamentos", value: filtered.value.length, sub: `${costList.value.length} tipos de custo`, icon: ClipboardList, tone: "bg-accent/10 text-accent" },
  { label: "Média Diária", value: formatBRL(avgDaily.value), sub: "por dia", icon: CalendarDays, tone: "bg-warning/10 text-warning" },
  { label: "Média Mensal", value: formatBRL(avgMonthly.value), sub: "por mês", icon: TrendingUp, tone: "bg-success/10 text-success" },
]);

/* ---------- cor por tipo de custo (consistente donut ↔ pill da tabela) ---------- */
const costEntries = computed(() => {
  const acc: Record<string, number> = {};
  for (const r of filtered.value) {
    const k = r.cost_name || "Outros";
    acc[k] = (acc[k] || 0) + Number(r.total_value || 0);
  }
  return Object.entries(acc).sort((a, b) => b[1] - a[1]);
});
const costColorMap = computed(() => {
  const m: Record<string, string> = {};
  costEntries.value.forEach(([label], i) => { m[label] = seriesColors[i % seriesColors.length]; });
  return m;
});
const costColor = (name?: string) => costColorMap.value[name || "Outros"] ?? "#9ca3af";

/* ---------- Gráfico 1: donut por tipo de custo ---------- */
const byCost = computed(() => ({
  labels: costEntries.value.map((e) => e[0]),
  datasets: [{ data: costEntries.value.map((e) => e[1]), backgroundColor: costEntries.value.map(([l]) => costColor(l)), borderWidth: 0 }],
}));
const costLegend = computed(() =>
  costEntries.value.map(([label, value]) => ({ label, value, color: costColor(label) })),
);
const donutOptions = { ...baseOptions, cutout: "68%", plugins: { legend: { display: false } } };

/* ---------- Gráfico 2: evolução mensal (área) ---------- */
const monthly = computed(() => {
  const acc: Record<string, number> = {};
  for (const r of filtered.value) {
    if (!r.date) continue;
    const k = r.date.slice(0, 7);
    acc[k] = (acc[k] || 0) + Number(r.total_value || 0);
  }
  const keys = Object.keys(acc).sort();
  const label = (k: string) => { const [y, m] = k.split("-"); return `${m}/${y.slice(2)}`; };
  return {
    labels: keys.map(label),
    datasets: [{
      label: "Custo", data: keys.map((k) => acc[k]),
      borderColor: palette.primary, backgroundColor: "rgba(251,191,36,0.12)",
      fill: true, tension: 0.35, pointRadius: 3, borderWidth: 2.5,
    }],
  };
});
const areaOptions = {
  ...baseOptions,
  plugins: { legend: { display: false } },
  scales: { x: { grid: { display: false } }, y: { ticks: { callback: brlTick } } },
};

/* ---------- paginação ---------- */
const page = ref(1);
const pageSize = 10;
const totalPages = computed(() => Math.max(1, Math.ceil(filtered.value.length / pageSize)));
const paged = computed(() => filtered.value.slice((page.value - 1) * pageSize, page.value * pageSize));
watch(filtered, () => { page.value = 1; });
const pageNumbers = computed(() => {
  const t = totalPages.value, c = page.value;
  const out: (number | "...")[] = [];
  for (let p = 1; p <= t; p++) {
    if (p === 1 || p === t || Math.abs(p - c) <= 1) {
      if (out.length && (out[out.length - 1] as number) < p - 1) out.push("...");
      out.push(p);
    }
  }
  return out;
});

/* ---------- formulário ---------- */
const dialogOpen = ref(false);
const editing = ref<OperationalCostRecord | null>(null);
const emptyForm = () => ({
  date: new Date().toISOString().slice(0, 10),
  cost_name: "", plate: "", vehicle_model: "", category_name: "",
  total_value: 0, km: null as number | null,
  supplier: "", invoice_number: "", attachment_url: "", observation: "",
});
const form = reactive(emptyForm());

function onPlate() {
  const v = vehByPlate.value[form.plate];
  form.vehicle_model = v?.vehicle_model ?? "";
  form.category_name = v?.category_name ?? "";
}
function openAdd() {
  editing.value = null;
  Object.assign(form, emptyForm());
  dialogOpen.value = true;
}
function openEdit(row: OperationalCostRecord) {
  editing.value = row;
  Object.assign(form, {
    date: row.date?.slice(0, 10), cost_name: row.cost_name, plate: row.plate ?? "",
    vehicle_model: row.vehicle_model ?? "", category_name: row.category_name ?? "",
    total_value: Number(row.total_value), km: row.km, supplier: row.supplier ?? "",
    invoice_number: row.invoice_number ?? "", attachment_url: row.attachment_url ?? "",
    observation: row.observation ?? "",
  });
  dialogOpen.value = true;
}
async function submit() {
  if (!form.cost_name) return toast.error("Selecione o tipo de custo");
  const payload = { ...form, plate: form.plate || null, km: form.km || null };
  const ok = editing.value ? await update(editing.value.id, payload) : await create(payload);
  if (ok) dialogOpen.value = false;
}

/* ---------- exclusão ---------- */
const deleteId = ref<string | null>(null);
async function confirmDelete() {
  if (deleteId.value) await remove(deleteId.value);
  deleteId.value = null;
}
</script>

<template>
  <div class="w-full p-6 md:p-10">
    <PageHeader title="Custos Operacionais" subtitle="Lançamentos de custos operacionais" :icon="DollarSign">
      <template #actions>
        <Button @click="openAdd"><Plus class="h-4 w-4" /> Novo Custo</Button>
      </template>
    </PageHeader>

    <!-- Resumo -->
    <div class="mb-6 grid grid-cols-2 gap-4 lg:grid-cols-4">
      <StatCard
        v-for="(s, i) in stats" :key="s.label"
        :label="s.label" :value="s.value" :sub="s.sub" :icon="s.icon" :tone="s.tone"
        :highlight="s.highlight" :delay="0.05 + i * 0.05"
      />
    </div>

    <!-- Gráficos -->
    <div v-if="!loading && items.length" class="mb-6 grid grid-cols-1 gap-4 lg:grid-cols-2">
      <ChartCard title="Custo por Tipo" caption="Participação por categoria" :delay="0.25">
        <div class="flex h-full items-center gap-5">
          <div class="relative h-full min-w-0 flex-1">
            <Doughnut :data="byCost" :options="donutOptions" />
            <div class="pointer-events-none absolute inset-0 flex flex-col items-center justify-center">
              <span class="text-[11px] font-semibold text-muted-foreground">Total</span>
              <span class="text-sm font-extrabold text-foreground">{{ formatBRL(total) }}</span>
            </div>
          </div>
          <ChartLegend class="flex-1" :items="costLegend" :total="total" />
        </div>
      </ChartCard>
      <ChartCard title="Evolução dos Custos" caption="Total por mês" :delay="0.3">
        <Line :data="monthly" :options="areaOptions" />
      </ChartCard>
    </div>

    <!-- Filtros -->
    <FilterBar :has-active="hasFilters" :delay="0.32" @clear="clearFilters">
      <label class="block"><span class="mb-1 block text-xs font-medium text-muted-foreground">De</span>
        <input v-model="filters.from" type="date" class="ui-input" />
      </label>
      <label class="block"><span class="mb-1 block text-xs font-medium text-muted-foreground">Até</span>
        <input v-model="filters.to" type="date" class="ui-input" />
      </label>
      <label class="block"><span class="mb-1 block text-xs font-medium text-muted-foreground">Custo</span>
        <select v-model="filters.costName" class="ui-input">
          <option value="">Todos</option>
          <option v-for="c in costNameOptions" :key="c" :value="c">{{ c }}</option>
        </select>
      </label>
      <label class="block"><span class="mb-1 block text-xs font-medium text-muted-foreground">Placa</span>
        <select v-model="filters.plate" class="ui-input">
          <option value="">Todas</option>
          <option v-for="p in plateOptions" :key="p" :value="p">{{ p }}</option>
        </select>
      </label>
    </FilterBar>

    <!-- Tabela -->
    <div v-if="loading" class="flex justify-center py-20"><Spinner /></div>
    <div v-else class="a-in overflow-hidden rounded-xl border bg-card shadow-card" style="animation-delay: 0.38s">
      <div class="flex items-center justify-between border-b p-4">
        <div class="flex items-center gap-2">
          <DollarSign class="h-4 w-4 text-primary" />
          <span class="text-sm font-bold uppercase tracking-wider">Lançamentos de Custos</span>
          <Badge>{{ filtered.length }}</Badge>
        </div>
        <span class="text-sm font-semibold">{{ formatBRL(total) }}</span>
      </div>

      <div class="scrollbar-brand overflow-x-auto">
        <table class="w-full text-sm">
          <thead class="bg-muted/50">
            <tr>
              <th class="th">Data</th>
              <th class="th">Veículo</th>
              <th class="th">Custo</th>
              <th class="th">Descrição</th>
              <th class="th">Fornecedor</th>
              <th class="th th-r">Valor (R$)</th>
              <th class="th th-r">Ações</th>
            </tr>
          </thead>
          <tbody>
            <tr v-if="paged.length === 0">
              <td colspan="7" class="py-12 text-center text-muted-foreground">Nenhum lançamento encontrado</td>
            </tr>
            <tr v-for="r in paged" :key="r.id" class="border-b transition-colors duration-200 hover:bg-primary/[0.06]">
              <!-- Data -->
              <td class="whitespace-nowrap px-4 py-2.5 font-medium">{{ formatDate(r.date) }}</td>
              <!-- Veículo -->
              <td class="whitespace-nowrap px-4 py-2.5">
                <div v-if="r.plate" class="flex items-center gap-2">
                  <div class="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-muted">
                    <Car class="h-3.5 w-3.5 text-muted-foreground" />
                  </div>
                  <div class="leading-tight">
                    <p class="text-sm font-bold tracking-widest">{{ r.plate }}</p>
                    <p v-if="r.vehicle_model || vehByPlate[r.plate]?.vehicle_model" class="text-xs text-muted-foreground">
                      {{ r.vehicle_model || vehByPlate[r.plate]?.vehicle_model }}
                    </p>
                  </div>
                </div>
                <span v-else class="text-xs text-muted-foreground">—</span>
              </td>
              <!-- Custo -->
              <td class="px-4 py-2.5">
                <span class="inline-flex items-center gap-1.5 rounded-full border bg-muted/40 px-2.5 py-1 text-xs font-semibold">
                  <span class="h-1.5 w-1.5 rounded-full" :style="{ background: costColor(r.cost_name) }" />
                  {{ r.cost_name || "—" }}
                </span>
              </td>
              <!-- Descrição -->
              <td class="px-4 py-2.5">
                <span class="block max-w-[200px] truncate text-xs text-muted-foreground" :title="r.observation ?? ''">{{ r.observation || "—" }}</span>
              </td>
              <!-- Fornecedor -->
              <td class="px-4 py-2.5">
                <div class="max-w-[160px] leading-tight">
                  <p class="truncate text-xs font-medium" :title="r.supplier ?? ''">{{ r.supplier || "—" }}</p>
                  <p v-if="r.invoice_number" class="text-xs text-muted-foreground">Nota: {{ r.invoice_number }}</p>
                </div>
              </td>
              <!-- Valor -->
              <td class="px-4 py-2.5 text-right font-semibold text-success tabular-nums">{{ formatBRL(r.total_value) }}</td>
              <!-- Ações -->
              <td class="px-4 py-2.5">
                <div class="flex items-center justify-end gap-1">
                  <button class="rounded-lg p-1.5 text-muted-foreground transition-colors hover:bg-muted hover:text-foreground" @click="openEdit(r)">
                    <Pencil class="h-3.5 w-3.5" />
                  </button>
                  <button class="rounded-lg p-1.5 text-muted-foreground transition-colors hover:bg-destructive/10 hover:text-destructive" @click="deleteId = r.id">
                    <Trash2 class="h-3.5 w-3.5" />
                  </button>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <!-- Rodapé + paginação -->
      <div class="flex flex-col items-center justify-between gap-3 border-t bg-muted/30 px-4 py-2.5 sm:flex-row">
        <span class="text-xs text-muted-foreground">{{ filtered.length }} de {{ items.length }} registro(s)</span>
        <div v-if="totalPages > 1" class="flex items-center gap-1">
          <button class="pg" :disabled="page === 1" @click="page = 1">«</button>
          <button class="pg" :disabled="page === 1" @click="page--">‹</button>
          <template v-for="(p, i) in pageNumbers" :key="i">
            <span v-if="p === '...'" class="px-1.5 text-xs text-muted-foreground">…</span>
            <button v-else class="pg" :class="p === page && 'border-primary bg-primary text-primary-foreground'" @click="page = (p as number)">{{ p }}</button>
          </template>
          <button class="pg" :disabled="page === totalPages" @click="page++">›</button>
          <button class="pg" :disabled="page === totalPages" @click="page = totalPages">»</button>
        </div>
      </div>
    </div>

    <!-- Formulário -->
    <Modal :open="dialogOpen" :title="editing ? 'Editar Custo' : 'Novo Custo Operacional'" :saving="saving" @close="dialogOpen = false" @submit="submit">
      <div class="grid grid-cols-2 gap-3">
        <FormField label="Data" required><input v-model="form.date" type="date" class="ui-input" /></FormField>
        <FormField label="Tipo de Custo" required>
          <select v-model="form.cost_name" class="ui-input">
            <option value="">Selecione...</option>
            <option v-for="c in costList" :key="c.id" :value="c.name">{{ c.name }}</option>
          </select>
        </FormField>
        <FormField label="Veículo (Placa) — opcional">
          <select v-model="form.plate" class="ui-input" @change="onPlate">
            <option value="">Sem veículo</option>
            <option v-for="v in vehicleList" :key="v.id" :value="v.plate">{{ v.plate }} — {{ v.vehicle_model }}</option>
          </select>
        </FormField>
        <FormField label="Valor Total (R$)" required><input v-model.number="form.total_value" type="number" step="0.01" class="ui-input" /></FormField>
        <FormField label="Fornecedor"><input v-model="form.supplier" class="ui-input" /></FormField>
        <FormField label="Nota Fiscal"><input v-model="form.invoice_number" class="ui-input" /></FormField>
        <FormField label="KM"><input v-model.number="form.km" type="number" class="ui-input" /></FormField>
        <FormField label="URL do Anexo"><input v-model="form.attachment_url" class="ui-input" placeholder="https://..." /></FormField>
        <FormField label="Observação" class="col-span-2"><input v-model="form.observation" class="ui-input" /></FormField>
      </div>
    </Modal>

    <!-- Confirmar exclusão -->
    <Modal :open="!!deleteId" title="Confirmar exclusão" submit-label="Excluir" @close="deleteId = null" @submit="confirmDelete">
      <p class="text-sm text-muted-foreground">Tem certeza que deseja excluir este lançamento? Esta ação não poderá ser desfeita.</p>
    </Modal>
  </div>
</template>

<style scoped>
.th {
  @apply px-4 py-2.5 text-left text-xs font-semibold uppercase tracking-wider text-muted-foreground;
}
.th-r {
  @apply text-right;
}
.pg {
  @apply flex h-7 min-w-[1.75rem] items-center justify-center rounded-md border bg-card px-1.5 text-xs font-medium transition-colors hover:bg-muted disabled:cursor-not-allowed disabled:opacity-40;
}
</style>

// src/pages/CustosOperacionais.jsx
import React, { useState, useMemo, useEffect } from 'react';
import { base44 } from '@/api/base44Client';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { motion } from 'framer-motion';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Plus, Pencil, Trash2, DollarSign, Car, Eye, Download } from 'lucide-react';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog';
import OperationalCostForm from '@/components/operational/OperationalCostForm';
import OperationalCostCharts from '@/components/operational/OperationalCostCharts';
import OperationalFiltersPanel from '@/components/operational/OperationalFiltersPanel';
import { format } from 'date-fns';

const formatCurrency = (v) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(v || 0);

const COST_COLORS = {
  'LAVAGEM DE VEÍCULOS': { bg: 'bg-blue-50', text: 'text-blue-700', dot: 'bg-blue-500' },
  'LAVAGEM DE VEICULOS': { bg: 'bg-blue-50', text: 'text-blue-700', dot: 'bg-blue-500' },
  'RASTREADOR DE VEÍCULOS': { bg: 'bg-emerald-50', text: 'text-emerald-700', dot: 'bg-emerald-500' },
  'RASTREADOR DE VEICULOS': { bg: 'bg-emerald-50', text: 'text-emerald-700', dot: 'bg-emerald-500' },
  'MULTAS DE TRÂNSITO': { bg: 'bg-red-50', text: 'text-red-700', dot: 'bg-red-500' },
  'MULTAS DE TRANSITO': { bg: 'bg-red-50', text: 'text-red-700', dot: 'bg-red-500' },
  'PEDÁGIO': { bg: 'bg-orange-50', text: 'text-orange-700', dot: 'bg-orange-500' },
  'PEDAGIO': { bg: 'bg-orange-50', text: 'text-orange-700', dot: 'bg-orange-500' },
  'SEGUROS DE VEÍCULOS': { bg: 'bg-purple-50', text: 'text-purple-700', dot: 'bg-purple-500' },
  'SEGURO': { bg: 'bg-purple-50', text: 'text-purple-700', dot: 'bg-purple-500' },
  'IPVA/LICENCIAMENTO': { bg: 'bg-yellow-50', text: 'text-yellow-700', dot: 'bg-yellow-500' },
  'ESTOQUE': { bg: 'bg-cyan-50', text: 'text-cyan-700', dot: 'bg-cyan-500' },
};

const COLOR_PALETTE = [
  { bg: 'bg-pink-50', text: 'text-pink-700', dot: 'bg-pink-500' },
  { bg: 'bg-teal-50', text: 'text-teal-700', dot: 'bg-teal-500' },
  { bg: 'bg-indigo-50', text: 'text-indigo-700', dot: 'bg-indigo-500' },
  { bg: 'bg-lime-50', text: 'text-lime-700', dot: 'bg-lime-500' },
  { bg: 'bg-rose-50', text: 'text-rose-700', dot: 'bg-rose-500' },
  { bg: 'bg-sky-50', text: 'text-sky-700', dot: 'bg-sky-500' },
  { bg: 'bg-amber-50', text: 'text-amber-700', dot: 'bg-amber-500' },
  { bg: 'bg-violet-50', text: 'text-violet-700', dot: 'bg-violet-500' },
];

const dynamicColorCache = {};
let colorIndex = 0;
const getCostStyle = (name) => {
  if (!name) return { bg: 'bg-slate-50', text: 'text-slate-700', dot: 'bg-slate-400' };
  if (COST_COLORS[name]) return COST_COLORS[name];
  if (!dynamicColorCache[name]) {
    dynamicColorCache[name] = COLOR_PALETTE[colorIndex % COLOR_PALETTE.length];
    colorIndex++;
  }
  return dynamicColorCache[name];
};

const PAGE_SIZE = 8;

export default function CustosOperacionais() {
  const queryClient = useQueryClient();
  const [showForm, setShowForm] = useState(false);
  const [editRecord, setEditRecord] = useState(null);
  const [deleteId, setDeleteId] = useState(null);
  const [currentPage, setCurrentPage] = useState(1);
  const [search, setSearch] = useState('');
  const [filters, setFilters] = useState({ dateFrom: '', dateTo: '', costName: 'all', plate: 'all' });

  const { data: records = [], isLoading } = useQuery({
    queryKey: ['operational-cost-records'],
    queryFn: () => base44.entities.OperationalCostRecord.list('-date', 10000),
  });

  const { data: vehicles = [] } = useQuery({
    queryKey: ['vehicles'],
    queryFn: () => base44.entities.Vehicle.list(),
  });

  const vehicleMap = useMemo(() => {
    const map = {};
    vehicles.forEach((v) => { map[v.plate] = v; });
    return map;
  }, [vehicles]);

  const createMutation = useMutation({
    mutationFn: (data) => base44.entities.OperationalCostRecord.create(data),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['operational-cost-records'] }); setShowForm(false); },
  });

  const updateMutation = useMutation({
    mutationFn: ({ id, data }) => base44.entities.OperationalCostRecord.update(id, data),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['operational-cost-records'] }); setShowForm(false); setEditRecord(null); },
  });

  const deleteMutation = useMutation({
    mutationFn: (id) => base44.entities.OperationalCostRecord.delete(id),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['operational-cost-records'] }),
  });

  const handleSubmit = (data) => {
    if (editRecord) updateMutation.mutate({ id: editRecord.id, data });
    else createMutation.mutate(data);
  };

  const costNameList = useMemo(() => [...new Set(records.map((r) => r.cost_name).filter(Boolean))].sort(), [records]);
  const plateList = useMemo(() => [...new Set(records.map((r) => r.plate).filter(Boolean))].sort(), [records]);

  const filtered = useMemo(() => {
    return records.filter((r) => {
      if (filters.dateFrom && r.date < filters.dateFrom) return false;
      if (filters.dateTo && r.date > filters.dateTo) return false;
      if (filters.costName !== 'all' && r.cost_name !== filters.costName) return false;
      if (filters.plate !== 'all' && r.plate !== filters.plate) return false;
      if (search) {
        const s = search.toLowerCase();
        const match = [r.cost_name, r.plate, r.supplier, r.invoice_number, r.observation].some(
          (v) => v && String(v).toLowerCase().includes(s)
        );
        if (!match) return false;
      }
      return true;
    });
  }, [records, filters, search]);

  useEffect(() => { setCurrentPage(1); }, [filters, search]);

  const totalValue = filtered.reduce((s, r) => s + (r.total_value || 0), 0);
  const totalPages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE));
  const paginated = filtered.slice((currentPage - 1) * PAGE_SIZE, currentPage * PAGE_SIZE);

  // Summary cards data
  const avgDaily = (() => {
    if (!filtered.length) return 0;
    const dates = filtered.map((r) => r.date).filter(Boolean).sort();
    if (dates.length < 2) return totalValue;
    const d1 = new Date(dates[0] + 'T12:00:00');
    const d2 = new Date(dates[dates.length - 1] + 'T12:00:00');
    const days = Math.max(1, Math.round((d2 - d1) / (1000 * 60 * 60 * 24)));
    return totalValue / days;
  })();

  const avgMonthly = (() => {
    const months = new Set(filtered.map((r) => r.date?.slice(0, 7)).filter(Boolean));
    return months.size > 0 ? totalValue / months.size : totalValue;
  })();

  const summaryCards = [
    { label: 'CUSTO TOTAL (PERÍODO)', value: formatCurrency(totalValue), icon: '💲', gradient: 'from-blue-500 to-blue-600', sub: `${filtered.length} lançamentos` },
    { label: 'TOTAL DE LANÇAMENTOS', value: filtered.length, icon: '📋', gradient: 'from-emerald-500 to-emerald-600', sub: `${costNameList.length} tipos de custo` },
    { label: 'CUSTO MÉDIO DIÁRIO', value: formatCurrency(avgDaily), icon: '📊', gradient: 'from-orange-500 to-orange-600', sub: 'Média por dia' },
    { label: 'CUSTO MÉDIO MENSAL', value: formatCurrency(avgMonthly), icon: '🚚', gradient: 'from-purple-500 to-purple-600', sub: 'Média por mês' },
  ];

  return (
    <div className="flex flex-col h-full min-h-screen bg-background">
      {/* Top bar */}
      <div className="flex items-center justify-between px-6 py-4 border-b bg-card">
        <h1 className="text-2xl font-bold text-foreground">Custos Operacionais</h1>
        <Button
          onClick={() => { setEditRecord(null); setShowForm(true); }}
          className="gap-2 bg-primary hover:bg-primary/90 text-white shadow-md px-5"
        >
          <Plus className="w-4 h-4" /> LANÇAR
        </Button>
      </div>

      <div className="flex flex-1 gap-0 overflow-hidden">
        {/* Main content */}
        <div className="flex-1 overflow-y-auto p-5 space-y-5">
          {/* Summary Cards */}
          <div className="grid grid-cols-2 xl:grid-cols-4 gap-3">
            {summaryCards.map((c, i) => (
              <div key={i} className={`rounded-xl bg-gradient-to-br ${c.gradient} text-white p-4 relative overflow-hidden shadow-md`}>
                <div className="absolute right-3 top-3 text-2xl opacity-70">{c.icon}</div>
                <p className="text-[10px] font-bold uppercase tracking-widest opacity-80 mb-1">{c.label}</p>
                <p className="text-xl font-bold leading-tight">{c.value}</p>
                <p className="text-[10px] opacity-70 mt-1">{c.sub}</p>
              </div>
            ))}
          </div>

          {/* Charts */}
          <OperationalCostCharts records={filtered} />

          {/* Table */}
          <div className="bg-card rounded-xl border shadow-sm overflow-hidden">
            <div className="flex items-center justify-between px-4 py-3 border-b">
              <div className="flex items-center gap-2">
                <DollarSign className="w-4 h-4 text-primary" />
                <span className="text-sm font-bold uppercase tracking-wider">LANÇAMENTOS DE CUSTOS</span>
                <Badge variant="outline" className="text-xs">{filtered.length}</Badge>
              </div>
              <div className="flex items-center gap-2">
                <Input
                  placeholder="Buscar..."
                  value={search}
                  onChange={(e) => setSearch(e.target.value)}
                  className="h-8 text-xs w-48"
                />
                <Button variant="outline" size="sm" className="h-8 gap-1 text-xs">
                  <Download className="w-3.5 h-3.5" /> Exportar
                </Button>
              </div>
            </div>

            {isLoading ? (
              <div className="flex items-center justify-center py-16">
                <div className="w-8 h-8 border-4 border-muted border-t-primary rounded-full animate-spin" />
              </div>
            ) : (
              <div className="overflow-x-auto">
                <Table>
                  <TableHeader>
                    <TableRow className="bg-muted/40">
                      <TableHead className="text-xs font-semibold uppercase text-muted-foreground">Data</TableHead>
                      <TableHead className="text-xs font-semibold uppercase text-muted-foreground">Veículo</TableHead>
                      <TableHead className="text-xs font-semibold uppercase text-muted-foreground">Custo</TableHead>
                      <TableHead className="text-xs font-semibold uppercase text-muted-foreground">Descrição</TableHead>
                      <TableHead className="text-xs font-semibold uppercase text-muted-foreground">Fornecedor</TableHead>
                      <TableHead className="text-xs font-semibold uppercase text-muted-foreground text-right">Valor (R$)</TableHead>
                      <TableHead className="text-xs font-semibold uppercase text-muted-foreground text-right w-24">Ações</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {filtered.length === 0 ? (
                      <TableRow>
                        <TableCell colSpan={7} className="text-center py-12 text-muted-foreground text-sm">
                          Nenhum lançamento encontrado
                        </TableCell>
                      </TableRow>
                    ) : paginated.map((r, idx) => {
                      const veh = vehicleMap[r.plate];
                      const model = veh?.vehicle_model || r.vehicle_model;
                      const style = getCostStyle(r.cost_name);
                      return (
                        <motion.tr
                          key={r.id}
                          initial={{ opacity: 0 }}
                          animate={{ opacity: 1 }}
                          transition={{ delay: idx * 0.01 }}
                          className="border-b hover:bg-muted/20 transition-colors"
                        >
                          <TableCell className="py-2.5 text-sm font-medium whitespace-nowrap">
                            {r.date ? format(new Date(r.date + 'T12:00:00'), 'dd/MM/yyyy') : '-'}
                          </TableCell>
                          <TableCell className="py-2.5">
                            {r.plate ? (
                              <div className="flex items-center gap-2">
                                <div className="w-7 h-7 rounded-lg bg-slate-100 flex items-center justify-center flex-shrink-0">
                                  <Car className="w-3.5 h-3.5 text-slate-400" />
                                </div>
                                <div>
                                  <p className="text-xs font-bold font-mono tracking-widest">{r.plate}</p>
                                  {model && <p className="text-[10px] text-muted-foreground">{model}</p>}
                                </div>
                              </div>
                            ) : <span className="text-muted-foreground text-xs">—</span>}
                          </TableCell>
                          <TableCell className="py-2.5">
                            <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-semibold ${style.bg} ${style.text}`}>
                              <span className={`w-1.5 h-1.5 rounded-full ${style.dot}`} />
                              {r.cost_name || '-'}
                            </span>
                          </TableCell>
                          <TableCell className="py-2.5 text-xs text-muted-foreground max-w-[180px]">
                            <span className="truncate block" title={r.observation}>{r.observation || '-'}</span>
                          </TableCell>
                          <TableCell className="py-2.5 text-xs font-medium max-w-[140px]">
                            <span className="truncate block" title={r.supplier}>{r.supplier || '-'}</span>
                          </TableCell>
                          <TableCell className="py-2.5 text-sm text-right font-bold text-emerald-600 tabular-nums">
                            {formatCurrency(r.total_value)}
                          </TableCell>
                          <TableCell className="py-2.5 text-right">
                            <div className="flex items-center justify-end gap-0.5">
                              <Button variant="ghost" size="icon" className="h-7 w-7 text-slate-400 hover:text-primary"
                                onClick={() => { setEditRecord(r); setShowForm(true); }}>
                                <Eye className="w-3.5 h-3.5" />
                              </Button>
                              <Button variant="ghost" size="icon" className="h-7 w-7 text-slate-400 hover:text-primary"
                                onClick={() => { setEditRecord(r); setShowForm(true); }}>
                                <Pencil className="w-3.5 h-3.5" />
                              </Button>
                              <Button variant="ghost" size="icon" className="h-7 w-7 text-slate-400 hover:text-destructive"
                                onClick={() => setDeleteId(r.id)}>
                                <Trash2 className="w-3.5 h-3.5" />
                              </Button>
                            </div>
                          </TableCell>
                        </motion.tr>
                      );
                    })}
                  </TableBody>
                </Table>
              </div>
            )}

            {/* Pagination */}
            {filtered.length > 0 && (
              <div className="px-4 py-3 border-t bg-muted/20 flex flex-col sm:flex-row items-center justify-between gap-2">
                <p className="text-xs text-muted-foreground">
                  Mostrando {Math.min((currentPage - 1) * PAGE_SIZE + 1, filtered.length)} a {Math.min(currentPage * PAGE_SIZE, filtered.length)} de {filtered.length} registros
                </p>
                <div className="flex items-center gap-1">
                  <button onClick={() => setCurrentPage(1)} disabled={currentPage === 1}
                    className="h-7 w-7 flex items-center justify-center rounded text-xs border bg-card hover:bg-muted disabled:opacity-40 disabled:cursor-not-allowed">‹‹</button>
                  <button onClick={() => setCurrentPage((p) => Math.max(1, p - 1))} disabled={currentPage === 1}
                    className="h-7 w-7 flex items-center justify-center rounded text-xs border bg-card hover:bg-muted disabled:opacity-40 disabled:cursor-not-allowed">‹</button>
                  {Array.from({ length: totalPages }, (_, i) => i + 1)
                    .filter((p) => p === 1 || p === totalPages || Math.abs(p - currentPage) <= 1)
                    .reduce((acc, p, idx, arr) => { if (idx > 0 && p - arr[idx - 1] > 1) acc.push('...'); acc.push(p); return acc; }, [])
                    .map((p, i) => p === '...' ?
                      <span key={`e-${i}`} className="h-7 w-7 flex items-center justify-center text-xs text-muted-foreground">…</span> :
                      <button key={p} onClick={() => setCurrentPage(p)}
                        className={`h-7 w-7 flex items-center justify-center rounded text-xs border transition-colors ${currentPage === p ? 'bg-primary text-white border-primary' : 'bg-card hover:bg-muted'}`}>{p}</button>
                    )}
                  <button onClick={() => setCurrentPage((p) => Math.min(totalPages, p + 1))} disabled={currentPage === totalPages}
                    className="h-7 w-7 flex items-center justify-center rounded text-xs border bg-card hover:bg-muted disabled:opacity-40 disabled:cursor-not-allowed">›</button>
                  <button onClick={() => setCurrentPage(totalPages)} disabled={currentPage === totalPages}
                    className="h-7 w-7 flex items-center justify-center rounded text-xs border bg-card hover:bg-muted disabled:opacity-40 disabled:cursor-not-allowed">››</button>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Right filters panel */}
        <div className="w-52 flex-shrink-0 border-l bg-card p-3 overflow-y-auto">
          <OperationalFiltersPanel
            filters={filters}
            setFilters={setFilters}
            costNameList={costNameList}
            plateList={plateList}
          />
        </div>
      </div>

      <OperationalCostForm
        open={showForm}
        onClose={() => { setShowForm(false); setEditRecord(null); }}
        onSubmit={handleSubmit}
        isLoading={createMutation.isPending || updateMutation.isPending}
        record={editRecord}
      />

      <AlertDialog open={!!deleteId} onOpenChange={() => setDeleteId(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Confirmar exclusão</AlertDialogTitle>
            <AlertDialogDescription>Tem certeza que deseja excluir este lançamento?</AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancelar</AlertDialogCancel>
            <AlertDialogAction className="bg-destructive hover:bg-destructive/90"
              onClick={() => { deleteMutation.mutate(deleteId); setDeleteId(null); }}>
              Excluir
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
