// frontend-vue/src/pages/Parametrizacoes.vue
<script setup lang="ts">
import { RouterLink } from "vue-router";
import { Layers, Truck, Fuel, Wrench, DollarSign, ArrowRight } from "lucide-vue-next";
import PageHeader from "@/components/ui/PageHeader.vue";

const groups = [
  { label: "Veículos", desc: "Categorias de veículos da frota", to: "/parametrizacoes/categorias", icon: Truck, tone: "bg-blue-500/10 text-blue-500", ready: true },
  { label: "Abastecimentos", desc: "Custos e tipos de combustíveis", to: "/parametrizacoes/abastecimentos", icon: Fuel, tone: "bg-orange-500/10 text-orange-500", ready: true },
  { label: "Manutenção", desc: "Classificações e tipos de manutenção", to: "/parametrizacoes/manutencao", icon: Wrench, tone: "bg-red-500/10 text-red-500", ready: true },
  { label: "Custos Operacionais", desc: "Custos administrativos diversos", to: "/parametrizacoes/operacionais", icon: DollarSign, tone: "bg-green-500/10 text-green-500", ready: true },
];
</script>

<template>
  <div class="w-full p-6 md:p-10">
    <PageHeader title="Estrutura dos Módulos" subtitle="Configure categorias, custos e regras de funcionamento de cada módulo" :icon="Layers" />
    <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
      <component
        :is="g.ready ? 'RouterLink' : 'div'"
        v-for="(g, i) in groups"
        :key="g.label"
        :to="g.ready ? g.to : undefined"
        class="a-in flex items-center gap-4 rounded-xl border bg-card p-5 shadow-card transition-all duration-300"
        :class="g.ready ? 'cursor-pointer hover:shadow-card-md hover:border-primary/50' : 'opacity-60'"
        :style="{ animationDelay: `${0.05 + i * 0.05}s` }"
      >
        <div class="flex h-11 w-11 items-center justify-center rounded-xl" :class="g.tone">
          <component :is="g.icon" class="h-6 w-6" />
        </div>
        <div class="flex-1">
          <p class="font-semibold">{{ g.label }}</p>
          <p class="text-xs text-muted-foreground">{{ g.desc }}</p>
        </div>
        <ArrowRight v-if="g.ready" class="h-4 w-4 text-muted-foreground" />
      </component>
    </div>
  </div>
</template>

// src/pages/Parametrizacoes.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Card, CardContent } from '@/components/ui/card';
import { Settings, Layers, ArrowRight, Sun, Moon, FileText } from 'lucide-react';
import PageHeader from '@/components/shared/PageHeader';
import { useTheme } from 'next-themes';

const container = {
  hidden: { opacity: 0 },
  show: { opacity: 1, transition: { staggerChildren: 0.1 } }
};

const item = {
  hidden: { opacity: 0, y: 15 },
  show: { opacity: 1, y: 0 }
};

export default function Parametrizacoes() {
  const { theme, setTheme } = useTheme();

  return (
    <div className="p-6 md:p-10 max-w-7xl mx-auto">
      <PageHeader
        title="Parametrizações"
        subtitle="Configurações gerais e regras de funcionamento do sistema"
        icon={Settings}
        iconColor="bg-accent/10"
        breadcrumbs={[
          { label: 'Dashboard', path: '/' },
          { label: 'Parametrizações' }
        ]}
      />

      <motion.div variants={container} initial="hidden" animate="show" className="grid grid-cols-1 sm:grid-cols-2 gap-5">

        {/* Theme Toggle Card */}
        <motion.div variants={item}>
          <Card className="border-0 shadow-lg shadow-amber-500/10 overflow-hidden">
            <div className="absolute inset-0 bg-gradient-to-br from-amber-400 to-orange-500 opacity-[0.06]" />
            <CardContent className="p-6 relative">
              <div className="flex items-start justify-between mb-4">
                <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-amber-400 to-orange-500 flex items-center justify-center shadow-md">
                  {theme === 'dark' ? <Moon className="w-6 h-6 text-white" /> : <Sun className="w-6 h-6 text-white" />}
                </div>
              </div>
              <h3 className="text-lg font-bold text-foreground mb-1">Aparência</h3>
              <p className="text-sm text-muted-foreground leading-relaxed mb-4">
                Alterne entre o tema claro e escuro do sistema.
              </p>
              <div className="flex items-center gap-2 p-1 rounded-xl bg-muted w-fit">
                <button
                  onClick={() => setTheme('light')}
                  className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-all duration-200 ${theme === 'light' ? 'bg-white text-foreground shadow-sm' : 'text-muted-foreground hover:text-foreground'}`}
                >
                  <Sun className="w-4 h-4" /> Claro
                </button>
                <button
                  onClick={() => setTheme('dark')}
                  className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-all duration-200 ${theme === 'dark' ? 'bg-slate-800 text-white shadow-sm' : 'text-muted-foreground hover:text-foreground'}`}
                >
                  <Moon className="w-4 h-4" /> Escuro
                </button>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        <motion.div variants={item}>
          <Link to="/relatorio">
            <Card className="group relative overflow-hidden border-0 shadow-lg shadow-blue-500/10 hover:shadow-xl hover:-translate-y-1 transition-all duration-300 cursor-pointer">
              <div className="absolute inset-0 bg-gradient-to-br from-blue-500 to-cyan-500 opacity-[0.06] group-hover:opacity-[0.1] transition-opacity" />
              <CardContent className="p-6 relative">
                <div className="flex items-start justify-between mb-4">
                  <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-blue-500 to-cyan-500 flex items-center justify-center shadow-md">
                    <FileText className="w-6 h-6 text-white" />
                  </div>
                  <ArrowRight className="w-5 h-5 text-muted-foreground group-hover:text-foreground group-hover:translate-x-1 transition-all" />
                </div>
                <h3 className="text-lg font-bold text-foreground mb-1">Relatório</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  Relatório geral consolidado com todos os custos lançados, gráficos dinâmicos e exportação em PDF.
                </p>
              </CardContent>
            </Card>
          </Link>
        </motion.div>

        <motion.div variants={item}>
          <Link to="/parametrizacoes/estrutura-modulos">
            <Card className="group relative overflow-hidden border-0 shadow-lg shadow-accent/10 hover:shadow-xl hover:-translate-y-1 transition-all duration-300 cursor-pointer">
              <div className="absolute inset-0 bg-gradient-to-br from-violet-500 to-purple-600 opacity-[0.06] group-hover:opacity-[0.1] transition-opacity" />
              <CardContent className="p-6 relative">
                <div className="flex items-start justify-between mb-4">
                  <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-violet-500 to-purple-600 flex items-center justify-center shadow-md">
                    <Layers className="w-6 h-6 text-white" />
                  </div>
                  <ArrowRight className="w-5 h-5 text-muted-foreground group-hover:text-foreground group-hover:translate-x-1 transition-all" />
                </div>
                <h3 className="text-lg font-bold text-foreground mb-1">Estrutura dos Módulos</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  Configuração de categorias, tipos de custo e regras de lançamento para cada módulo do sistema.
                </p>
              </CardContent>
            </Card>
          </Link>
        </motion.div>
      </motion.div>
    </div>
  );
}
